import { useParams } from "react-router-dom";
import { useState } from "react";
import TopHeader from "../components/layout/TopHeader";
import DarkMarketplaceNav from "../components/layout/DarkMarketplaceNav";
import Footer from "../components/layout/Footer";
import PageContainer from "../components/layout/PageContainer";
import RightArrow from "../components/ui/RightArrow";
import GradientUnderline from "../components/ui/GradientUnderline";
import Modal from "../components/ui/Modal";
import SolutionDetailsModal from "../components/sections/SolutionDetailsModal";

// Detailed solution data
const SOLUTION_DETAILS = {
  "Real Time Loan Application Fraud Detection": {
    idea: [
      "Problem statement/opportunity: Increase in the cases of fraud and financial crime.",
      "Persona: Front office operations staff",
      "Scope: Initiate fraud detection and remediation on real time.",
      "Approach: AI Agent implementation to trigger the workflows for real time fraud detection and initiating the steps to prevent those. Traditional and existing algorithms such as pattern recognition etc. will be used, which AI agent will invoke as per the need."
    ],
    benefits: [
      "Reduced risk due to real time fraud prevention.",
      "Cost saving by reducing human intervention."
    ],
    demonstration: [
      "Simulate a fraud scenario – example – identity theft for account opening.",
      "Show visual representation of the AI agents and activities triggered in real time.",
      "Show how the remedial actions are taken in case of fraud on screen."
    ]
  },
  "Credit card transaction fraud detection agent": {
    idea: [
      "Problem statement/opportunity: New types of payment frauds are happening leaving scope for zero-day vulnerability.",
      "Still all frauds are not caught on time.",
      "False-positive cases may stop genuine payment scenario"
    ],
    benefits: [
      "Fraud detection percentage will improve.",
      "False-positive cases will be reduced.",
      "Identify new ways to commit the fraud to prevent those. This will help the bank stay ahead of curve and reduce the risk of zero-day vulnerability.",
      "Reduction in personnel cost over the time, as AI agent matures."
    ],
    demonstration: [
      "Goal oriented AI agents with following objectives",
      "Agent 1: Identify new models and/or parameters by analyzing existing known fraud scenarios.",
      "Agent 2: Identify avenues to commit fraud by generating new scenarios based on the process documentation and transaction or other data.",
      "Agent 3: Create description about the analysis done and scenarios generated by Agent 1 and 2.",
      "These agents will be provided with the historic data and models used for fraud detection.",
      "Human in the loop – Fraud risk management team will review the potential threat signal and provide feedback."
    ]
  },
  "AML SAR Generation Workflow - Agentic AI": {
    idea: [
      "Problem statement/opportunity: Use Generative AI to extract key details, summarize cases accurately, and rank them based on urgency and impact.",
      "This ensures faster decision-making, enhanced compliance, and improved customer satisfaction, while reducing operational inefficiencies i.e., false positive",
      "Scope: Detect, investigate, and report potentially suspicious transactions to regulators like FIU-IND (India) or FinCEN (USA)",
      "Personas: Banks and financial entities, managing a high volume of customer cases and regulatory inquiries, Audit & Risk teams, Compliance managers"
    ],
    benefits: [
      "Cost Savings: Reduced manual effort for SAR drafting and QA",
      "Regulatory Compliance: Lower risk of non-compliance fines and regulatory scrutiny",
      "Actionable Insights: Enhanced strategic decision-making based on SAR trends and analytics",
      "Accelerating Investigation & Reporting Timelines"
    ],
    demonstration: [
      "User authentication",
      "Upload/Simulate a Suspicious Case",
      "Use AI for Document / input files Analysis",
      "Generate SAR Narrative Using LLM",
      "Display Editable SAR Draft for human approval",
      "Export or File to the authority"
    ]
  },
  "AI-Driven document analysis and generation solution - Agentic AI": {
    idea: [
      "Problem statement/opportunity: Customizable application that permits users to extract relevant and actionable insights from uploaded files primarily based on a defined set of criteria or conditions and to reference the existing documents and generate draft documents with updated insights",
      "Persona: Compliance Officer, Policy Lead, Fund Manager, Auditors",
      "Scope: Guarantees traceability to original documents via bringing up sources. Presents AI-generated recommendations for updates in policy. Automates the document drafting method with human moderation checkpoint"
    ],
    benefits: [
      "Automates extraction of actionable insights from large document sets",
      "Integrates existing policies to streamline updates and revisions",
      "Reduces time to create compliant policy documents by providing AI-generated drafts",
      "Ensures traceability between the original data, insights, and new policies."
    ],
    demonstration: [
      "Upload Documents and Criteria File",
      "Pre-defined system prompt guides the generative AI in summarizing, extracting, and generating data based on the user defined criteria.",
      "The platform generates a structured output summarizing the extracted information based on the user-defined conditions and criteria with precise citations to the document for human moderation.",
      "Human moderator reviews the generated draft file to ensure compliance with the existing policies and procedures and remove biases.",
      "The approver finalizes the changes and uses the platform to generate new or updated policy documents."
    ]
  },
  "Common Domain Model": {
    idea: [
      "Problem statement/opportunity: The Integrated Payment Command Center is a real-time, AI-powered dashboard that serves as a centralized space to monitor and control critical payment operations.",
      "Scope: Should be able to capture real time data from underlying various payment systems for providing a unified view to the payments operations administration through its different layers and components for decision support to respond to the real time events.",
      "Persona: Operations head, Risk & Compliance team, Treasury & Cash Management"
    ],
    benefits: [
      "Holistic representation of Payment Operations",
      "Highlight performance against business SLAs",
      "Raise alerts for exception and incidents",
      "Pattern analysis drives efficiency and predictive ops",
      "Real-time fund flow visibility enables optimal liquidity management"
    ],
    demonstration: [
      "Scenario Setup for the client",
      "Live Dashboard Demonstration with Real-time transactions across all payment modes",
      "Visual alerts on failed/delayed transactions",
      "Root Cause Analysis (via AI Assistant)",
      "Action Trigger Demo - User clicks on alert: Escalates to payment ops, Auto-initiates retry for failed transactions",
      "Insights Dashboard - Historical data trends show: Which branch/corridor has most delays, Volume spike predictions for next 24 hours, Heatmap of anomalies"
    ]
  },
  "AI enabled Investment Advisory and Portfolio construction and balancing - Agentic AI": {
    idea: [
      "Problem statement/opportunity: Provide cost-effective human like interaction for low to middle income groups during creation of customer profile and investment strategy.",
      "Persona: Tech savvy wealth management customer",
      "Scope: Create customer profile and investment strategy using digital avatar of relationship manager and conversational AI.",
      "Approach: Role of AI is to just converse with the customer. Investment strategy will be prepared with traditional approach."
    ],
    benefits: [
      "Cost saving by reducing human involvement to serve the masses.",
      "Enhanced customer experience as compared to simple form-based website."
    ],
    demonstration: [
      "Set up will involve a big TV screen and a smart table in Customer service zone.",
      "Visitor will be displayed a digital avatar on a big screen.",
      "Smart table will be used to capture and show the customer details and display investment strategy."
    ]
  },
  "AI Powered Smart Fund Lending Platform": {
    idea: [
      "Problem statement/opportunity: Customers are sold unwanted banking products. They are not offered the needed products.",
      "They cannot take risk with certain decision as they don't understand how to mitigate that risk.",
      "They don't know how to best use the banking product."
    ],
    benefits: [
      "Retail banks will be able to sell more and relevant products to the customer.",
      "Better cross-selling and up-selling.",
      "Better customer retention and engagement.",
      "Better CLTV - Customer lifetime value."
    ],
    demonstration: [
      "Customer's actual financial data and other demographic details will be captured.",
      "Options for Home, travel, commute, and shop will be provided.",
      "Customer will choose one option and based on choices, they would see the balanced scorecard.",
      "Customer can view how they have performed and how to improve."
    ]
  }
};

// Define solutions for each category
const CATEGORY_SOLUTIONS = {
  "retail-banking": {
    title: "Retail Banking",
    solutions: [
      {
        title: "Real Time Loan Application Fraud Detection",
        description: "",
        image: "rb01.jpg",
        link: "http://real-time-fraud-detection-app.s3-website-us-west-2.amazonaws.com/loan-dashboard"
      },
      {
        title: "AI Powered Smart Fund Lending Platform",
        description: "",
        image: "rb02.png"
      }
    ]
  },
  "commercial-banking": {
    title: "Commercial Banking",
    solutions: [
      {
        title: "Real Time Loan Application Fraud Detection",
        description: "",
        image: "cb01.jpg",
        link: "http://real-time-fraud-detection-app.s3-website-us-west-2.amazonaws.com/loan-dashboard"
      },
      {
        title: "AI Powered Smart Fund Lending Platform",
        description: "",
        image: "cb02.png"
      }
    ]
  },
  "investment-banking": {
    title: "Investment Banking",
    solutions: [
      {
        title: "Real Time Loan Application Fraud Detection",
        description: "",
        image: "ib01.jpg",
        link: "http://real-time-fraud-detection-app.s3-website-us-west-2.amazonaws.com/loan-dashboard"
      },
      {
        title: "AI Powered Smart Fund Lending Platform",
        description: "",
        image: "ib02.png"
      }
    ]
  },
  "cards-payments": {
    title: "Cards and payment",
    solutions: [
      {
        title: "Real Time Loan Application Fraud Detection",
        description: "",
        image: "cap01.jpg",
        link: "http://real-time-fraud-detection-app.s3-website-us-west-2.amazonaws.com/loan-dashboard"
      },
      {
        title: "Credit card transaction fraud detection agent",
        description: "",
        image: "cap02.png"
      }
    ]
  },
  "risk-compliance": {
    title: "Risk & Compliance",
    solutions: [
      {
        title: "Credit card transaction fraud detection agent",
        description: "",
        image: "rac01.png"
      },
      {
        title: "AML SAR Generation Workflow - Agentic AI",
        description: "",
        image: "rac02.png",
        link: "https://n2i9wremfi.us-west-2.awsapprunner.com/"
      },
      {
        title: "AI-Driven document analysis and generation solution - Agentic AI",
        description: "",
        image: "rac03.png",
        link: "https://sjp3mwhjhn.us-west-2.awsapprunner.com/"
      }
    ]
  },
  "asset-wealth-management": {
    title: "Asset and Wealth Management",
    solutions: [
      {
        title: "AI enabled Investment Advisory and Portfolio construction and balancing - Agentic AI",
        description: "",
        image: "awm01.png"
      },
      {
        title: "Common Domain Model",
        description: "",
        image: "awm02.png",
        link: "https://hk9pjj82vm.us-west-2.awsapprunner.com/signin"
      }
    ]
  }
};

export default function CategorySolutionsPage() {
  const { category } = useParams();
  const categoryData = CATEGORY_SOLUTIONS[category];
  const [selectedSolution, setSelectedSolution] = useState(null);
  const [isModalOpen, setIsModalOpen] = useState(false);

  const handleCardClick = (solution) => {
    const solutionDetails = SOLUTION_DETAILS[solution.title];
    if (solutionDetails) {
      setSelectedSolution({
        title: solution.title,
        description: solution.description,
        ...solutionDetails
      });
      setIsModalOpen(true);
    }
  };

  const handleCloseModal = () => {
    setIsModalOpen(false);
    setTimeout(() => setSelectedSolution(null), 300);
  };

  // If category not found, show error
  if (!categoryData) {
    return (
      <div className="w-full">
        <TopHeader />
        <DarkMarketplaceNav />
        <section className="w-full bg-white py-[60px]">
          <PageContainer>
            <h2 className="text-[#00005A] font-bold text-[32px] leading-[36px]">
              Category not found
            </h2>
          </PageContainer>
        </section>
        <Footer />
      </div>
    );
  }

  return (
    <div className="w-full">
      <TopHeader />
      <DarkMarketplaceNav />
      <section className="w-full bg-white py-[60px]">
        <PageContainer>
          <div className="mb-[40px] inline-block">
            <h2 className="text-[#00005A] font-bold text-[32px] leading-[36px] mb-[8px]">
              {categoryData.title}
            </h2>
            <GradientUnderline />
          </div>

          {/* Solutions Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-[32px]">
            {categoryData.solutions.map((solution, index) => (
              <div
                key={index}
                className="border border-[#D0D0CE] bg-white overflow-hidden hover:shadow-lg transition-shadow cursor-pointer rounded-[8px]"
                onClick={() => handleCardClick(solution)}
              >
                {/* Image Container */}
                <div className="w-full h-[200px] bg-gradient-to-br from-[#001F54] to-[#003D8F] flex items-center justify-center overflow-hidden">
                  <img
                    src={`/assets/images/${solution.image}`}
                    alt={solution.title}
                    className="w-full h-full object-cover"
                  />
                </div>

                {/* Content */}
                <div className="p-[24px]">
                  <h3 className="text-[#5B9BD5] font-semibold text-[18px] leading-[22px] hover:underline cursor-pointer">
                    {solution.title}
                  </h3>
                </div>
              </div>
            ))}
          </div>
        </PageContainer>
      </section>

      {/* Modal */}
      {selectedSolution && (
        <Modal
          isOpen={isModalOpen}
          onClose={handleCloseModal}
          title={selectedSolution.title}
        >
          <SolutionDetailsModal solution={selectedSolution} />
        </Modal>
      )}

      <Footer />
    </div>
  );
}
