import { useParams } from "react-router-dom";
import { useState } from "react";
import TopHeader from "../components/layout/TopHeader";
import DarkMarketplaceNav from "../components/layout/DarkMarketplaceNav";
import Footer from "../components/layout/Footer";
import PageContainer from "../components/layout/PageContainer";
import RightArrow from "../components/ui/RightArrow";
import GradientUnderline from "../components/ui/GradientUnderline";
import Modal from "../components/ui/Modal";
import SolutionDetailsModal from "../components/sections/SolutionDetailsModal";

// Detailed solution data
const SOLUTION_DETAILS = {
  "Real Time Loan Application Fraud Detection": {
    idea: [
      "Problem statement/opportunity: Increase in the cases of fraud and financial crime.",
      "Persona: Front office operations staff",
      "Scope: Initiate fraud detection and remediation on real time.",
      "Approach: AI Agent implementation to trigger the workflows for real time fraud detection and initiating the steps to prevent those. Traditional and existing algorithms such as pattern recognition etc. will be used, which AI agent will invoke as per the need."
    ],
    benefits: [
      "Reduced risk due to real time fraud prevention.",
      "Cost saving by reducing human intervention."
    ],
    demonstration: [
      "Simulate a fraud scenario – example – identity theft for account opening.",
      "Show visual representation of the AI agents and activities triggered in real time.",
      "Show how the remedial actions are taken in case of fraud on screen."
    ]
  },
  "Credit card transaction fraud detection agent": {
    idea: [
      "Problem statement/opportunity: New types of payment frauds are happening leaving scope for zero-day vulnerability.",
      "Still all frauds are not caught on time.",
      "False-positive cases may stop genuine payment scenario"
    ],
    benefits: [
      "Fraud detection percentage will improve.",
      "False-positive cases will be reduced.",
      "Identify new ways to commit the fraud to prevent those. This will help the bank stay ahead of curve and reduce the risk of zero-day vulnerability.",
      "Reduction in personnel cost over the time, as AI agent matures."
    ],
    demonstration: [
      "Goal oriented AI agents with following objectives",
      "Agent 1: Identify new models and/or parameters by analyzing existing known fraud scenarios.",
      "Agent 2: Identify avenues to commit fraud by generating new scenarios based on the process documentation and transaction or other data.",
      "Agent 3: Create description about the analysis done and scenarios generated by Agent 1 and 2.",
      "These agents will be provided with the historic data and models used for fraud detection.",
      "Human in the loop – Fraud risk management team will review the potential threat signal and provide feedback."
    ]
  },
  "AML SAR Generation Workflow - Agentic AI": {
    idea: [
      "Problem statement/opportunity: Use Generative AI to extract key details, summarize cases accurately, and rank them based on urgency and impact.",
      "This ensures faster decision-making, enhanced compliance, and improved customer satisfaction, while reducing operational inefficiencies i.e., false positive",
      "Scope: Detect, investigate, and report potentially suspicious transactions to regulators like FIU-IND (India) or FinCEN (USA)",
      "Personas: Banks and financial entities, managing a high volume of customer cases and regulatory inquiries, Audit & Risk teams, Compliance managers"
    ],
    benefits: [
      "Cost Savings: Reduced manual effort for SAR drafting and QA",
      "Regulatory Compliance: Lower risk of non-compliance fines and regulatory scrutiny",
      "Actionable Insights: Enhanced strategic decision-making based on SAR trends and analytics",
      "Accelerating Investigation & Reporting Timelines"
    ],
    demonstration: [
      "User authentication",
      "Upload/Simulate a Suspicious Case",
      "Use AI for Document / input files Analysis",
      "Generate SAR Narrative Using LLM",
      "Display Editable SAR Draft for human approval",
      "Export or File to the authority"
    ]
  },
  "AI-Driven document analysis and generation solution - Agentic AI": {
    idea: [
      "Problem statement/opportunity: Customizable application that permits users to extract relevant and actionable insights from uploaded files primarily based on a defined set of criteria or conditions and to reference the existing documents and generate draft documents with updated insights",
      "Persona: Compliance Officer, Policy Lead, Fund Manager, Auditors",
      "Scope: Guarantees traceability to original documents via bringing up sources. Presents AI-generated recommendations for updates in policy. Automates the document drafting method with human moderation checkpoint"
    ],
    benefits: [
      "Automates extraction of actionable insights from large document sets",
      "Integrates existing policies to streamline updates and revisions",
      "Reduces time to create compliant policy documents by providing AI-generated drafts",
      "Ensures traceability between the original data, insights, and new policies."
    ],
    demonstration: [
      "Upload Documents and Criteria File",
      "Pre-defined system prompt guides the generative AI in summarizing, extracting, and generating data based on the user defined criteria.",
      "The platform generates a structured output summarizing the extracted information based on the user-defined conditions and criteria with precise citations to the document for human moderation.",
      "Human moderator reviews the generated draft file to ensure compliance with the existing policies and procedures and remove biases.",
      "The approver finalizes the changes and uses the platform to generate new or updated policy documents."
    ]
  },
  "Common Domain Model": {
    idea: [
      "Problem statement/opportunity: The Integrated Payment Command Center is a real-time, AI-powered dashboard that serves as a centralized space to monitor and control critical payment operations.",
      "Scope: Should be able to capture real time data from underlying various payment systems for providing a unified view to the payments operations administration through its different layers and components for decision support to respond to the real time events.",
      "Persona: Operations head, Risk & Compliance team, Treasury & Cash Management"
    ],
    benefits: [
      "Holistic representation of Payment Operations",
      "Highlight performance against business SLAs",
      "Raise alerts for exception and incidents",
      "Pattern analysis drives efficiency and predictive ops",
      "Real-time fund flow visibility enables optimal liquidity management"
    ],
    demonstration: [
      "Scenario Setup for the client",
      "Live Dashboard Demonstration with Real-time transactions across all payment modes",
      "Visual alerts on failed/delayed transactions",
      "Root Cause Analysis (via AI Assistant)",
      "Action Trigger Demo - User clicks on alert: Escalates to payment ops, Auto-initiates retry for failed transactions",
      "Insights Dashboard - Historical data trends show: Which branch/corridor has most delays, Volume spike predictions for next 24 hours, Heatmap of anomalies"
    ]
  },
  "AI enabled Investment Advisory and Portfolio construction and balancing - Agentic AI": {
    idea: [
      "Problem statement/opportunity: Provide cost-effective human like interaction for low to middle income groups during creation of customer profile and investment strategy.",
      "Persona: Tech savvy wealth management customer",
      "Scope: Create customer profile and investment strategy using digital avatar of relationship manager and conversational AI.",
      "Approach: Role of AI is to just converse with the customer. Investment strategy will be prepared with traditional approach."
    ],
    benefits: [
      "Cost saving by reducing human involvement to serve the masses.",
      "Enhanced customer experience as compared to simple form-based website."
    ],
    demonstration: [
      "Set up will involve a big TV screen and a smart table in Customer service zone.",
      "Visitor will be displayed a digital avatar on a big screen.",
      "Smart table will be used to capture and show the customer details and display investment strategy."
    ]
  },
  "AI Powered Smart Fund Lending Platform": {
    idea: [
      "Problem statement/opportunity: Customers are sold unwanted banking products. They are not offered the needed products.",
      "They cannot take risk with certain decision as they don't understand how to mitigate that risk.",
      "They don't know how to best use the banking product."
    ],
    benefits: [
      "Retail banks will be able to sell more and relevant products to the customer.",
      "Better cross-selling and up-selling.",
      "Better customer retention and engagement.",
      "Better CLTV - Customer lifetime value."
    ],
    demonstration: [
      "Customer's actual financial data and other demographic details will be captured.",
      "Options for Home, travel, commute, and shop will be provided.",
      "Customer will choose one option and based on choices, they would see the balanced scorecard.",
      "Customer can view how they have performed and how to improve."
    ]
  },
  "Portfolio Rebalancing": {
    fullDescription: "Designed for high-net-worth complexity, this platform continuously evaluates portfolio drift against institutional-grade market outlooks and individual investor profiles. It empowers advisors with intelligent, automated recommendations that justify every trade through the lens of long-term investment goals and historical performance patterns."
  },
  "Commercial Banking - Client Onboarding - Compliance Checks": {
    fullDescription: "Explore the future of regulatory compliance and client intake with a comprehensive Agentic AI framework designed to handle complex legal document screening, UBO identification, and global PEP/Sanctions monitoring for the corporate customer. Featuring an \"AI-First\" workflow, the solution ensures 95% data accuracy and provides stakeholders with transparent, real-time dashboards to manage corporate risk with unprecedented precision."
  },
  "User Personalization for Asset & Wealth Management": {
    fullDescription: "This solution unifies fragmented market and client data into a trusted 360-degree view to generate hyper-personalized insights and next best actions. By automating life-event-driven engagements with human-in-the-loop validation, it empowers advisors to deliver scalable, compliant, and deeply resonant client experiences."
  },
  "Portfolio Exception Monitor": {
    fullDescription: "The solution engine monitors concentration risks and market sentiment in near real-time to prevent breach scenarios. It combines rules-based controls with domain-aware generative insights to deliver client-specific alerts, contextual explanations, and recommended actions for advisors. The platform streamlines the advisor's response through automated explanations and direct order management connectivity for rapid, compliant portfolio adjustments."
  },
  "Wealth Management - Life Stage Simulator (POV: Clients and Financial Advisor)": {
    fullDescription: "A modern, interactive platform enabling clients and RMs to model different life stage goals with real-time validation delivering personalized preparedness scores, guided inputs, saved scenarios, and professional reports—empowering Advisors and clients to co-create informed financial decisions through a beautifully designed, seamless digital journey."
  },
  "KYC Processing": {
    fullDescription: "This solution eliminates fragmented, labor-intensive workflows by deploying intelligent agents that autonomously verify documentation and unify disparate data in real-time. By automating the end-to-end lifecycle, it slashes processing times and removes manual bottlenecks, ensuring a frictionless customer experience without compromising rigorous regulatory standards."
  },
  "Fraud and Dispute Management": {
    fullDescription: "By reimagining dispute management through agentification, this solution enables banks to offer rapid, intelligent, and transparent fraud resolution journeys. It combines specialized agents for evidence gathering and risk assessment with human-in-the-loop validation, ensuring every dispute is handled with both operational efficiency and the precision required for regulatory compliance."
  },
  "Invisible Payment Solution": {
    fullDescription: "SmartPay is an invisible payment solution that enables customers to shop and pay seamlessly without traditional checkouts. Using biometric authentication and a wallet-based payment model, purchases are completed automatically without scanning items, swiping cards, or using mobile devices. The solution includes a User App for onboarding and wallet management, and a Shopping App for real-time authentication and instant payment during checkout."
  },
  "Trade Reconciliation and Exception Management": {
    fullDescription: "By agentifying the trade reconciliation journey, this solution bridges the gap between middle-office silos through automated error clustering and predictive outlier detection. The system intelligently learns from past resolutions to execute autonomous remedial actions, ensuring post-trade confirmations and settlements remain compliant, efficient, and free from manual handoff delays."
  },
  "Synthetic Data Generation": {
    fullDescription: "This agentic solution streamlines the creation of synthetic financial datasets to provide a rich foundation for training highly accurate anti-money laundering models. By intelligently increasing the sample size of fraudulent transactions, the platform ensures that machine learning assets are rigorously prepared to defend the bank's ecosystem against evolving financial crimes."
  }
};

// Define solutions for each category
const CATEGORY_SOLUTIONS = {
  "retail-banking": {
    title: "Retail Banking",
    solutions: [
      {
        title: "Real Time Loan Application Fraud Detection",
        description: "",
        image: "rb01.jpg",
        link: "http://real-time-fraud-detection-app.s3-website-us-west-2.amazonaws.com/loan-dashboard"
      },
      {
        title: "AI Powered Smart Fund Lending Platform",
        description: "",
        image: "rb02.png"
      },
      {
        title: "KYC Processing",
        description: "",
        image: "Orchestrating Seamless Compliance via Autonomous Agentic KYC Transformation.jpeg",
        link: "https://cognizantonline-my.sharepoint.com/:v:/r/personal/113135_cognizant_com/Documents/Documents/C%20Drive/Framework%20Tools%20%26%20Accelerators/Agentic%20AI/Agents%20Foundry/Solution%20Demo/33.%20Agentic%20Solution%20-%20KYC%20Processes/Automated%20KYC%20Processes.mp4?csf=1&web=1&e=ZeqOwy&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D"
      }
    ]
  },
  "commercial-banking": {
    title: "Commercial Banking",
    solutions: [
      {
        title: "Real Time Loan Application Fraud Detection",
        description: "",
        image: "cb01.jpg",
        link: "http://real-time-fraud-detection-app.s3-website-us-west-2.amazonaws.com/loan-dashboard"
      },
      {
        title: "AI Powered Smart Fund Lending Platform",
        description: "",
        image: "cb02.png"
      },
      {
        title: "Commercial Banking - Client Onboarding - Compliance Checks",
        description: "",
        image: "Intelligent Automation Corporate Banking Next-Gen KYB through Agentic AI.jpeg",
        link: "https://cognizantonline-my.sharepoint.com/:v:/r/personal/113135_cognizant_com/Documents/Documents/C%20Drive/Framework%20Tools%20%26%20Accelerators/Agentic%20AI/Agents%20Foundry/Solution%20Demo/13.%20Commercial%20Banking%20-%20Client%20Onboarding/13_Commercial%20Banking_Client%20Onboarding.mp4?csf=1&web=1&e=W4NHua&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D"
      }
    ]
  },
  "investment-banking": {
    title: "Investment Banking",
    solutions: [
      {
        title: "Real Time Loan Application Fraud Detection",
        description: "",
        image: "ib01.jpg",
        link: "http://real-time-fraud-detection-app.s3-website-us-west-2.amazonaws.com/loan-dashboard"
      },
      {
        title: "AI Powered Smart Fund Lending Platform",
        description: "",
        image: "ib02.png"
      }
    ]
  },
  "cards-payments": {
    title: "Cards and payment",
    solutions: [
      {
        title: "Real Time Loan Application Fraud Detection",
        description: "",
        image: "cap01.jpg",
        link: "http://real-time-fraud-detection-app.s3-website-us-west-2.amazonaws.com/loan-dashboard"
      },
      {
        title: "Credit card transaction fraud detection agent",
        description: "",
        image: "cap02.png"
      },
      {
        title: "Fraud and Dispute Management",
        description: "",
        image: "Transforming Fraud and Dispute Resolution Through Agentic Intelligence.jpeg",
        link: "https://cognizantonline-my.sharepoint.com/:v:/r/personal/113135_cognizant_com/Documents/Documents/C%20Drive/Framework%20Tools%20%26%20Accelerators/Agentic%20AI/Agents%20Foundry/Solution%20Demo/34.%20Agentic%20Solution%20-%20Fraud%20%26%20Dispute%20Management/Fraud%20and%20Dispute%20Management.mp4?csf=1&web=1&e=wQEaPa&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D"
      },
      {
        title: "Invisible Payment Solution",
        description: "",
        image: "InvisiblePaymentSolutions.png",
        link: "https://cognizantonline-my.sharepoint.com/:v:/r/personal/2101809_cognizant_com/Documents/Microsoft%20Teams%20Chat%20Files/SmartPay_Shopping_App_Demo.mp4?csf=1&web=1&e=xQe3fE&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D"
      }
    ]
  },
  "risk-compliance": {
    title: "Risk & Compliance",
    solutions: [
      {
        title: "Credit card transaction fraud detection agent",
        description: "",
        image: "rac01.png"
      },
      {
        title: "AML SAR Generation Workflow - Agentic AI",
        description: "",
        image: "rac02.png",
        link: "https://n2i9wremfi.us-west-2.awsapprunner.com/"
      },
      {
        title: "AI-Driven document analysis and generation solution - Agentic AI",
        description: "",
        image: "rac03.png",
        link: "https://sjp3mwhjhn.us-west-2.awsapprunner.com/"
      }
    ]
  },
  "asset-wealth-management": {
    title: "Asset and Wealth Management",
    solutions: [
      {
        title: "AI enabled Investment Advisory and Portfolio construction and balancing - Agentic AI",
        description: "",
        image: "awm01.png"
      },
      {
        title: "Common Domain Model",
        description: "",
        image: "awm02.png",
        link: "https://hk9pjj82vm.us-west-2.awsapprunner.com/signin"
      },
      {
        title: "Portfolio Rebalancing",
        description: "",
        image: "Next-Gen Agentic Engine for Context-Aware HNW Portfolio Optimization.jpeg",
        link: "https://cognizantonline-my.sharepoint.com/:v:/r/personal/113135_cognizant_com/Documents/Documents/C%20Drive/Framework%20Tools%20%26%20Accelerators/Agentic%20AI/Agents%20Foundry/Solution%20Demo/01.%20Portfolio%20Rebalancing/Portfolio%20Rebalancing%20-%20Demo.mp4?csf=1&web=1&e=1hSqdk&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D"
      },
      {
        title: "User Personalization for Asset & Wealth Management",
        description: "",
        image: "Driving Hyper-Personalized Wealth Journeys via Autonomous Agents.jpeg",
        link: "https://cognizantonline-my.sharepoint.com/:v:/r/personal/113135_cognizant_com/Documents/Documents/C%20Drive/Framework%20Tools%20%26%20Accelerators/Agentic%20AI/Agents%20Foundry/Solution%20Demo/22.%20Vibe%20Coding_User%20Personalization%20Solution/Vibe%20Coding%20User%20Personalization%20Demo%20Final%20-%20Video%20(1).mp4?csf=1&web=1&e=lKqpBU&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D"
      },
      {
        title: "Portfolio Exception Monitor",
        description: "",
        image: "Proactive Portfolio Resilience with Agentic Exception Monitoring.jpeg",
        link: "https://cognizantonline-my.sharepoint.com/:v:/r/personal/113135_cognizant_com/Documents/Documents/C%20Drive/Framework%20Tools%20%26%20Accelerators/Agentic%20AI/Agents%20Foundry/Solution%20Demo/23.%20Vibe%20Coding_Portfolio%20Exception%20Monitor/23_Demo%20Video_Vibe%20Coding_Portfolio%20Exception%20Monitor_Rajdeep.mp4?csf=1&web=1&e=l7Iwbf&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D"
      },
      {
        title: "Wealth Management - Life Stage Simulator (POV: Clients and Financial Advisor)",
        description: "",
        image: "Empowering Financial Preparedness Through Agentic Goal Modeling.jpeg",
        link: "https://cognizantonline-my.sharepoint.com/:v:/r/personal/113135_cognizant_com/Documents/Documents/C%20Drive/Framework%20Tools%20%26%20Accelerators/Agentic%20AI/Agents%20Foundry/Solution%20Demo/24.%20Wealth%20Management%20Life%20Stage%20Simulator/24.%20Wealth%20Management%20Life%20Stage%20Simulator%20(POV%20Clients%20and%20Financial%20Advisor).mp4?csf=1&web=1&e=ObvatY&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D"
      }
    ]
  },
  "capital-market": {
    title: "Capital Market",
    solutions: [
      {
        title: "Trade Reconciliation and Exception Management",
        description: "",
        image: "Transforming Post-Trade Integrity Through Agentic Reconciliation Orchestration.jpeg",
        link: "https://cognizantonline-my.sharepoint.com/:v:/r/personal/113135_cognizant_com/Documents/Documents/C%20Drive/Framework%20Tools%20%26%20Accelerators/Agentic%20AI/Agents%20Foundry/Solution%20Demo/43%20Trade%20Reconciliation%20and%20Exception%20Management/Exception%20Management%20Demo.mp4?csf=1&web=1&e=LdTO5C&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D"
      }
    ]
  },
  "data-management": {
    title: "Data Management",
    solutions: [
      {
        title: "Synthetic Data Generation",
        description: "",
        image: "Empowering Advanced Fraud Detection via Automated Synthetic Data Generation.jpeg",
        link: "https://cognizantonline-my.sharepoint.com/:v:/r/personal/113135_cognizant_com/Documents/Documents/C%20Drive/Framework%20Tools%20%26%20Accelerators/Agentic%20AI/Agents%20Foundry/Solution%20Demo/46.%20Synthetic%20Data%20Generation/Synthetic%20Data%20Generation%20for%20Fraud%20Detection%20Demo.mp4?csf=1&web=1&e=JHhscM&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D"
      }
    ]
  }
};

export default function CategorySolutionsPage() {
  const { category } = useParams();
  const categoryData = CATEGORY_SOLUTIONS[category];
  const [selectedSolution, setSelectedSolution] = useState(null);
  const [isModalOpen, setIsModalOpen] = useState(false);

  const handleCardClick = (solution) => {
    const solutionDetails = SOLUTION_DETAILS[solution.title];
    if (solutionDetails) {
      setSelectedSolution({
        title: solution.title,
        description: solution.description,
        link: solution.link || null,
        ...solutionDetails
      });
      setIsModalOpen(true);
    }
  };

  const handleCloseModal = () => {
    setIsModalOpen(false);
    setTimeout(() => setSelectedSolution(null), 300);
  };

  // If category not found, show error
  if (!categoryData) {
    return (
      <div className="w-full">
        <TopHeader />
        <DarkMarketplaceNav />
        <section className="w-full bg-white py-[60px]">
          <PageContainer>
            <h2 className="text-[#00005A] font-bold text-[32px] leading-[36px]">
              Category not found
            </h2>
          </PageContainer>
        </section>
        <Footer />
      </div>
    );
  }

  return (
    <div className="w-full">
      <TopHeader />
      <DarkMarketplaceNav />
      <section className="w-full bg-white py-[60px]">
        <PageContainer>
          <div className="mb-[40px] inline-block">
            <h2 className="text-[#00005A] font-bold text-[32px] leading-[36px] mb-[8px]">
              {categoryData.title}
            </h2>
            <GradientUnderline />
          </div>

          {/* Solutions Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-[32px]">
            {categoryData.solutions.map((solution, index) => (
              <div
                key={index}
                className="border border-[#D0D0CE] bg-white overflow-hidden hover:shadow-lg transition-shadow cursor-pointer rounded-[8px]"
                onClick={() => handleCardClick(solution)}
              >
                {/* Image Container */}
                <div className="w-full h-[200px] bg-gradient-to-br from-[#001F54] to-[#003D8F] flex items-center justify-center overflow-hidden">
                  <img
                    src={`/assets/images/${solution.image}`}
                    alt={solution.title}
                    className="w-full h-full object-cover"
                  />
                </div>

                {/* Content */}
                <div className="p-[24px]">
                  <h3 className="text-[#5B9BD5] font-semibold text-[18px] leading-[22px] hover:underline cursor-pointer">
                    {solution.title}
                  </h3>
                </div>
              </div>
            ))}
          </div>
        </PageContainer>
      </section>

      {/* Modal */}
      {selectedSolution && (
        <Modal
          isOpen={isModalOpen}
          onClose={handleCloseModal}
          title={selectedSolution.title}
        >
          <SolutionDetailsModal solution={selectedSolution} />
        </Modal>
      )}

      <Footer />
    </div>
  );
}
