import { useParams, useLocation, useNavigate } from "react-router-dom";
import { useState } from "react";
import TopHeader from "../components/layout/TopHeader";
import DarkMarketplaceNav from "../components/layout/DarkMarketplaceNav";
import Footer from "../components/layout/Footer";
import PageContainer from "../components/layout/PageContainer";
import RightArrow from "../components/ui/RightArrow";
import Modal from "../components/ui/Modal";
import SolutionDetailsModal from "../components/sections/SolutionDetailsModal";

// Detailed solution data
const SOLUTION_DETAILS = {
  "Real Time Loan Application Fraud Detection": {
    problemStatement: "Increase in the cases of fraud and financial crime, with high dependency on manual intervention for detection and remediation.",
    idea: {
      opportunity: "Initiate fraud detection and remediation on real time to reduce risk and operational cost.",
      personas: "Front office operations staff",
      scope: "Initiate fraud detection and remediation on real time.",
      approach: "AI Agent implementation to trigger the workflows for real time fraud detection and initiating the steps to prevent those. Traditional and existing algorithms such as pattern recognition will be used, which AI agent will invoke as per the need."
    },
    benefits: [
      "Reduced risk due to real time fraud prevention.",
      "Cost saving by reducing human intervention."
    ],
    demonstration: [
      "Simulate a fraud scenario – example – identity theft for account opening.",
      "Show visual representation of the AI agents and activities triggered in real time.",
      "Show how the remedial actions are taken in case of fraud on screen."
    ]
  },
  "Credit card transaction fraud detection agent": {
    problemStatement: "New types of payment frauds are happening leaving scope for zero-day vulnerability. Still all frauds are not caught on time, and false-positive cases may stop genuine payment scenarios.",
    idea: {
      opportunity: "Improve fraud detection percentage, reduce false-positives, and proactively identify new fraud patterns to stay ahead of evolving threats.",
      personas: "Fraud Risk Management team, Bank Operations",
      scope: "Identify new fraud models, generate fraud scenarios, and provide analysis based on historic data and process documentation.",
      approach: "Goal-oriented multi-agent AI system with human-in-the-loop validation by the fraud risk management team."
    },
    specializedAgents: [
      "Agent 1: Identify new models/parameters by analyzing existing known fraud scenarios.",
      "Agent 2: Identify avenues to commit fraud by generating new scenarios based on process documentation and transaction data.",
      "Agent 3: Create description of the analysis done and scenarios generated by Agent 1 and 2."
    ],
    benefits: [
      "Fraud detection percentage will improve.",
      "False-positive cases will be reduced.",
      "Identify new ways to commit fraud to prevent those — bank stays ahead of curve and reduces zero-day vulnerability.",
      "Reduction in personnel cost over time as AI agent matures."
    ],
    demonstration: [
      "Goal oriented AI agents with defined objectives.",
      "Agents fed with historic data and existing fraud detection models.",
      "Agent 1: Identifies new models/parameters from known fraud scenarios.",
      "Agent 2: Generates new fraud scenarios from process docs and transaction data.",
      "Agent 3: Produces analysis description and scenario report.",
      "Human in the loop – Fraud risk management team reviews potential threat signals and provides feedback."
    ]
  },
  "AML SAR Generation Workflow - Agentic AI": {
    problemStatement: "Use Generative AI to extract key details, summarize cases accurately, and rank them based on urgency and impact. This ensures faster decision-making, enhanced compliance, and improved customer satisfaction while reducing operational inefficiencies i.e., false positives.",
    idea: {
      opportunity: "Automate SAR narrative report generation to report potentially suspicious transactions to regulators like FIU-IND (India) or FinCEN (USA), reducing manual effort and compliance risk.",
      personas: "Banks and financial entities managing a high volume of customer cases and regulatory inquiries, Audit & Risk teams, Compliance managers",
      scope: "SAR narrative report generation to report potentially suspicious transactions to regulators like FIU-IND (India) or FinCEN (USA).",
      approach: "Multi-agent workflow: Preprocessor, Flagging agent, SAR Narrative agent, Evaluator agent, Report formator agent."
    },
    specializedAgents: [
      "Preprocessor Agent",
      "Flagging Agent",
      "SAR Narrative Agent",
      "Evaluator Agent",
      "Report Formator Agent"
    ],
    benefits: [
      "Cost Savings: Reduced manual effort for SAR drafting and QA",
      "Regulatory Compliance: Lower risk of non-compliance fines and regulatory scrutiny",
      "Actionable Insights: Enhanced strategic decision-making based on SAR trends and analytics",
      "Accelerating Investigation & Reporting Timelines"
    ],
    demonstration: [
      "Step 1: User authentication",
      "Step 2: Upload/Simulate a Suspicious Case",
      "Step 3: Use AI for Document / input files Analysis",
      "Step 4: Generate SAR Narrative Using LLM",
      "Step 5: Display Editable SAR Draft for human approval",
      "Step 6: Export or File to the authority"
    ]
  },
  "AI-Driven document analysis and generation solution - Agentic AI": {
    problemStatement: "Organizations need a customizable application that permits users to extract relevant and actionable insights from uploaded files based on defined criteria, and to reference existing documents to generate draft documents with updated insights.",
    idea: {
      opportunity: "Automate extraction of actionable insights from large document sets and streamline policy update workflows with AI-generated drafts and full traceability.",
      personas: "Compliance Officer, Policy Lead, Fund Manager, Auditors",
      scope: "Guarantees traceability to original documents via citing sources. Presents AI-generated recommendations for policy updates. Automates document drafting with human moderation checkpoint.",
      approach: "Generative AI with pre-defined system prompts to summarize, extract, and generate data based on user-defined criteria, with citations and human moderation."
    },
    benefits: [
      "Automates extraction of actionable insights from large document sets",
      "Integrates existing policies to streamline updates and revisions",
      "Reduces time to create compliant policy documents by providing AI-generated drafts",
      "Ensures traceability between the original data, insights, and new policies."
    ],
    demonstration: [
      "Step 1: Upload Documents and Criteria File",
      "Step 2: Pre-defined system prompt guides the generative AI in summarizing, extracting, and generating data based on user-defined criteria.",
      "Step 3: Platform generates structured output summarizing extracted information with precise citations for human moderation.",
      "Step 4: Human moderator reviews the generated draft to ensure compliance and remove biases.",
      "Step 5: Approver finalizes changes and generates new or updated policy documents."
    ]
  },
  "Common Domain Model": {
    problemStatement: "Payment operations administration lacks a centralized, real-time view across underlying payment systems, making it difficult to respond to events and SLAs in time.",
    idea: {
      opportunity: "The Integrated Payment Command Center is a real-time, AI-powered dashboard that serves as a centralized space to monitor and control critical payment operations.",
      personas: "Operations Head, Risk & Compliance team, Treasury & Cash Management",
      scope: "Capture real time data from underlying payment systems for a unified view to payments operations administration through different layers and components for decision support to respond to real time events.",
      approach: "Real-time AI-powered command center with live dashboards, alerts, root cause analysis, and pattern-based predictive operations."
    },
    benefits: [
      "Holistic representation of Payment Operations",
      "Highlight performance against business SLAs",
      "Raise alerts for exceptions and incidents",
      "Pattern analysis drives efficiency and predictive ops",
      "Real-time fund flow visibility enables optimal liquidity management"
    ],
    demonstration: [
      "Step 1: Scenario Setup for the client",
      "Step 2: Live Dashboard Demonstration with Real-time transactions across all payment modes",
      "Step 3: Visual alerts on failed/delayed transactions",
      "Step 4: Root Cause Analysis (via AI Assistant)",
      "Step 5: Action Trigger – Escalate to payment ops, auto-initiate retry for failed transactions",
      "Step 6: Insights Dashboard – Historical trends, volume spike predictions, anomaly heatmap"
    ]
  },
  "AI enabled Investment Advisory and Portfolio construction and balancing - Agentic AI": {
    problemStatement: "Low-to-middle-income customers cannot afford one-on-one wealth manager engagement during customer profiling and investment strategy creation.",
    idea: {
      opportunity: "Provide cost-effective human-like interaction for low to middle income groups during creation of customer profile and investment strategy.",
      personas: "Tech savvy wealth management customer",
      scope: "Create customer profile and investment strategy using digital avatar of relationship manager and conversational AI.",
      approach: "AI converses with the customer to capture inputs; traditional investment strategy engine prepares the recommendation."
    },
    benefits: [
      "Cost saving by reducing human involvement to serve the masses.",
      "Enhanced customer experience as compared to simple form-based website."
    ],
    demonstration: [
      "Step 1: Set up a big TV screen and a smart table in customer service zone.",
      "Step 2: Visitor sees a digital avatar on a big screen.",
      "Step 3: Smart table captures customer details and displays investment strategy."
    ]
  },
  "AI Powered Smart Fund Lending Platform": {
    problemStatement: "Customers are sold unwanted banking products, not offered relevant ones, cannot make risk-informed decisions, and don't know how to optimally use banking products.",
    idea: {
      opportunity: "Help retail banks cross-sell and up-sell the right products at the right time using AI-driven scoring and persona modeling.",
      personas: "Retail Banking Customers, Relationship Managers, Cross-sell Teams",
      scope: "Capture customer's financial data and demographics, model life options (home/travel/commute/shop), and produce a balanced scorecard for guided decisions.",
      approach: "Persona-driven scoring with scenario simulation and balanced scorecard outputs to enable better cross-sell and customer engagement."
    },
    benefits: [
      "Retail banks will be able to sell more and relevant products to the customer.",
      "Better cross-selling and up-selling.",
      "Better customer retention and engagement.",
      "Better CLTV — Customer lifetime value."
    ],
    demonstration: [
      "Step 1: Customer's financial data and demographic details captured.",
      "Step 2: Options for Home, Travel, Commute, and Shop provided.",
      "Step 3: Customer chooses one option and sees the balanced scorecard.",
      "Step 4: Customer views performance and improvement guidance."
    ]
  },
  "Portfolio Rebalancing": {
    problemStatement: "Portfolio rebalancing is critical but inefficient and manual-heavy. Limited real-time visibility across assets & geographies leads to delayed decisions. High dependency on expert analysts → cost + scalability issue. Risk of portfolio drift, missed market signals, and suboptimal outcomes.",
    idea: {
      opportunity: "Shift from periodic (quarterly/manual) rebalancing to continuous, intelligent rebalancing. Enable hyper-personalized portfolios for HNW clients at scale. Improve RM productivity + advisory quality. Build regulator-ready, explainable recommendations.",
      personas: "Relationship Manager (RM) / Wealth Advisor, Portfolio Manager, HNW / Ultra-HNW Client, Risk & Compliance Officer",
      scope: "Portfolio monitoring (multi-asset, multi-geography), Risk profiling & investment objective alignment, Market data ingestion + news signals, Portfolio drift detection & rebalancing recommendation, Suitability validation + human-in-loop approval.",
      approach: "\"Sense → Reason → Act\" model"
    },
    specializedAgents: [
      "Client Profiling Agent",
      "Portfolio Analysis Agent",
      "Market Intelligence Agent",
      "Suitability & Compliance Agent",
      "Simulation & Optimization Agent",
      "Recommendation Agent",
      "RM Assist Agent (Human-in-loop)"
    ],
    benefits: [
      "Increased advisory penetration & client engagement",
      "3–5x RM productivity improvement",
      "Reduced client churn in high-value segments",
      "Faster recommendation cycle: hours → minutes",
      "Lower dependency on manual analysis",
      "Reduced human errors in decision-making",
      "Better alignment with client goals & risk profile",
      "Continuous portfolio optimization vs static periodic review",
      "Improved risk-return performance visibility",
      "Explainable, regulator-ready recommendations",
      "Built-in suitability validation",
      "Full audit trail of decisions"
    ],
    demonstration: [
      "Step 1: Client Portfolio Load",
      "Step 2: Real-time Market Sync",
      "Step 3: Drift Detection",
      "Step 4: AI Recommendation",
      "Step 5: Scenario Simulation",
      "Step 6: RM Approval Flow",
      "Step 7: Final Output"
    ]
  },
  "Commercial Banking - Client Onboarding - Compliance Checks": {
    problemStatement: "Corporate onboarding is slow, manual, and compliance-heavy. Challenges in document collection, verification, and screening. High risk of errors, delays, and regulatory non-compliance.",
    idea: {
      opportunity: "Enable AI-first, automated KYB onboarding. Real-time compliance screening (KYC, AML, PEP, Sanctions). Faster onboarding with higher accuracy and transparency.",
      personas: "Relationship Manager (RM), Compliance / AML Officer, Corporate Client (Business User)",
      scope: "End-to-end corporate onboarding: capture inputs, extract & validate documents, compliance screening (KYC/AML/PEP/Sanctions), real-time status and risk decisioning.",
      approach: "Multi-agent workflow (AI orchestration): Capture minimal client inputs → Extract & validate data (OCR + NLP) → Perform compliance checks → Provide real-time status + risk decision. Fully AI-driven onboarding with human-in-loop review."
    },
    specializedAgents: [
      "Orchestration Agent",
      "Data Extraction Agent",
      "Compliance Agent",
      "Monitoring Agent"
    ],
    benefits: [
      "Faster corporate onboarding",
      "Improved customer experience (reduced friction)",
      "Reduced manual effort in document verification",
      "Lower onboarding turnaround time",
      "Higher data accuracy",
      "Automated regulatory checks & screening",
      "Reduced compliance risk and errors",
      "Real-time risk visibility dashboards"
    ],
    demonstration: [
      "Step 1: Client Initiation",
      "Step 2: Document Processing",
      "Step 3: Compliance Screening",
      "Step 4: Risk Evaluation",
      "Step 5: Real-time Dashboard",
      "Step 6: Final Decision"
    ]
  },
  "User Personalization for Asset & Wealth Management": {
    problemStatement: "Client data is fragmented across systems, limiting personalization. Advisors struggle to deliver timely, relevant engagement.",
    idea: {
      opportunity: "Create 360° client view + hyper-personalized insights. Enable life-event-driven engagement at scale.",
      personas: "Relationship Manager / Wealth Advisor, HNW Client",
      scope: "Client + market data aggregation, Personalization of insights & next best actions, Life-event-driven recommendations.",
      approach: "Agentic AI-driven personalization layer: Unify client + market data → Generate insights & next best actions → Trigger personalized journeys with RM validation. Human-in-loop ensures compliance + trust."
    },
    specializedAgents: [
      "Data Aggregation Agent – Builds 360° client view",
      "Insight Generation Agent – Generates personalized insights",
      "Recommendation Agent – Recommends next best actions",
      "Engagement Agent – Triggers personalized client interactions",
      "RM Assist Agent – Enables human validation"
    ],
    benefits: [
      "Hyper-personalized client experience",
      "Increased engagement & cross-sell",
      "Scalable personalization across clients",
      "Reduced manual effort for advisors",
      "Human-in-loop validation ensures control",
      "Explainable recommendations"
    ],
    demonstration: [
      "Step 1: Client data + market data unified",
      "Step 2: 360° client profile generated",
      "Step 3: AI generates insights & next best actions",
      "Step 4: Personalized recommendations presented",
      "Step 5: RM reviews & approves",
      "Step 6: Personalized engagement triggered"
    ]
  },
  "Portfolio Exception Monitor": {
    problemStatement: "Portfolio risks (concentration, market events) are detected late. Limited visibility leads to breach scenarios and delayed action.",
    idea: {
      opportunity: "Enable real-time exception monitoring & proactive alerts. Provide context-aware, explainable insights for faster decisions.",
      personas: "Wealth Advisor / RM, Portfolio Manager",
      scope: "Portfolio risk & concentration monitoring, Market sentiment tracking, Exception alerts & recommendations.",
      approach: "Agentic monitoring engine (real-time): Track portfolio + market signals continuously → Detect breaches / risk deviations → Generate alerts with explanation + actions → Enable quick execution via order systems. Proactive → not reactive portfolio management."
    },
    specializedAgents: [
      "Monitoring Agent – Tracks portfolio & market signals",
      "Risk Detection Agent – Identifies concentration risks & breaches",
      "Insight Agent – Generates contextual explanations",
      "Recommendation Agent – Suggests corrective actions",
      "Execution Agent – Connects to order management for action"
    ],
    benefits: [
      "Proactive portfolio risk management",
      "Improved client trust & advisory quality",
      "Faster response to market events",
      "Reduced manual monitoring effort",
      "Early breach detection",
      "Explainable, compliant recommendations"
    ],
    demonstration: [
      "Step 1: Portfolio + market data monitored in real time",
      "Step 2: System detects exception (risk / concentration breach)",
      "Step 3: AI generates alert with explanation",
      "Step 4: Recommended actions suggested",
      "Step 5: Advisor reviews & executes via integrated system"
    ]
  },
  "Wealth Management - Life Stage Simulator (POV: Clients and Financial Advisor)": {
    problemStatement: "Clients lack clarity on financial readiness across life stages. Planning is often static, manual, and not scenario-driven.",
    idea: {
      opportunity: "Enable interactive life-stage goal simulation. Provide real-time preparedness scores & insights.",
      personas: "HNW Client, Wealth Advisor / RM",
      scope: "Life-stage goal planning (education, retirement, etc.), Scenario modeling & simulations, Personalized reports & insights.",
      approach: "Agentic goal simulation platform: Capture client goals & inputs → Simulate multiple life scenarios → Generate preparedness score + insights → Enable co-creation with RM. Interactive + explainable financial planning journey."
    },
    specializedAgents: [
      "Goal Modeling Agent – Simulates life-stage scenarios",
      "Data Processing Agent – Captures & validates client inputs",
      "Insight Agent – Generates preparedness score & recommendations",
      "Report Generation Agent – Creates advisor-ready reports",
      "RM Assist Agent – Enables collaborative planning"
    ],
    benefits: [
      "Enhanced client engagement & trust",
      "Improved advisory-led planning",
      "Faster scenario analysis",
      "Standardized, scalable advisory process",
      "Clear financial preparedness visibility",
      "Personalized, goal-based recommendations"
    ],
    demonstration: [
      "Step 1: Client inputs life goals & financial details",
      "Step 2: System simulates multiple scenarios",
      "Step 3: Preparedness score generated",
      "Step 4: Insights & recommendations shown",
      "Step 5: RM collaborates & refines plan",
      "Step 6: Final report generated"
    ]
  },
  "KYC Processing": {
    problemStatement: "KYC is fragmented, manual, and time-consuming. Leads to delays, errors, and poor customer experience.",
    idea: {
      opportunity: "Enable end-to-end automated KYC lifecycle. Faster onboarding with accurate, compliant processing.",
      personas: "Retail Banking Customer, KYC Analyst / Operations Team",
      scope: "Customer onboarding (KYC), Document ingestion & verification, Compliance & risk checks.",
      approach: "Agentic AI-driven KYC automation: Capture & validate customer documents → Perform automated compliance checks → Generate decision & audit trail. Seamless, real-time KYC processing."
    },
    specializedAgents: [
      "Intake Agent – Captures customer data & documents",
      "Document Processing Agent – Extracts & validates data (OCR/NLP)",
      "Due Diligence Agent – Performs KYC/AML checks",
      "Decision Agent – Final review & approval",
      "Communication Agent – Updates customer & stakeholders",
      "Client Liaison Agent",
      "Case Closure Agent",
      "Final Review Agent",
      "FinCrime Agent"
    ],
    benefits: [
      "Faster onboarding & improved customer experience",
      "Reduced manual effort & processing time",
      "Higher accuracy in document verification",
      "Automated regulatory checks",
      "Complete audit trail & reduced risk"
    ],
    demonstration: [
      "Step 1: Customer submits KYC details & documents",
      "Step 2: AI extracts & validates data",
      "Step 3: Compliance checks performed automatically",
      "Step 4: Risk / eligibility assessed",
      "Step 5: Final decision communicated"
    ]
  },
  "Fraud and Dispute Management": {
    problemStatement: "Fraud & dispute handling is manual, slow, and inconsistent. Requires multiple data sources → delays & errors.",
    idea: {
      opportunity: "Enable intelligent, automated dispute resolution. Improve speed, accuracy, and transparency for customers.",
      personas: "Customer (Card holder), Fraud / Dispute Analyst",
      scope: "Fraud detection & dispute intake, Evidence gathering & validation, Risk assessment & resolution.",
      approach: "Agentic AI-driven dispute workflow: Capture dispute request → Gather evidence across systems → Assess fraud risk → Generate resolution with human validation. Fast, transparent, compliant resolution journey."
    },
    specializedAgents: [
      "Intake Agent – Captures dispute request",
      "Evidence Gathering Agent – Collects transaction & case data",
      "Risk Assessment Agent – Evaluates fraud likelihood",
      "Resolution Agent – Suggests dispute outcome",
      "Communication Agent – Updates customer & stakeholders",
      "Case Classification Agent",
      "Customer Profile Agent",
      "Merchant Profile Agent",
      "Case Evaluation Agent",
      "Fraud Evidence Agent",
      "Representment Agent",
      "Pre-arbitration Agent",
      "Case Chargeback Agent"
    ],
    benefits: [
      "Faster dispute resolution",
      "Improved customer trust & satisfaction",
      "Reduced manual effort in investigations",
      "Faster turnaround time",
      "Consistent fraud assessment",
      "Transparent, auditable decision-making"
    ],
    demonstration: [
      "Step 1: Customer raises dispute",
      "Step 2: AI collects transaction & case data",
      "Step 3: Fraud risk analyzed",
      "Step 4: Resolution recommendation generated",
      "Step 5: Analyst validates decision",
      "Step 6: Outcome communicated to customer"
    ]
  },
  "Invisible Payment Solution": {
    technology: "Azure",
    problemStatement: "Payment step adds friction (queues, devices, manual checkout). Impacts customer experience and increases merchant cost.",
    idea: {
      opportunity: "Enable checkout-free, invisible payments. Deliver seamless, frictionless shopping experience.",
      personas: "Retail Customer, Merchant / Store Operator",
      scope: "Customer onboarding (biometric + wallet), In-store authentication & purchase tracking, Automatic payment processing.",
      approach: "Biometric + wallet-based invisible payment system: Customer authentication (biometric) → Items auto-detected during shopping → Payment triggered automatically at exit. No checkout, no device, no manual payment step."
    },
    specializedAgents: [
      "Identity & Authentication Agent – Verifies customer (biometric)",
      "Shopping Context Agent – Tracks purchase journey",
      "Item Detection Agent – Identifies items selected",
      "Payment Agent – Triggers wallet-based payment",
      "Notification Agent – Shares bill & confirmation"
    ],
    benefits: [
      "Reduced checkout infrastructure cost",
      "Increased customer stickiness via wallet model",
      "Eliminates queues & checkout delays",
      "Fully automated payment lifecycle",
      "Frictionless, \"walk-in → walk-out\" experience",
      "No cards, cash, or devices required"
    ],
    demonstration: [
      "Step 1: Customer registers biometric & wallet",
      "Step 2: Enters store → authenticated instantly",
      "Step 3: Items automatically detected (RFID / smart basket)",
      "Step 4: Customer exits → context ends",
      "Step 5: Payment auto-deducted from wallet",
      "Step 6: Digital invoice generated"
    ]
  },
  "Trade Reconciliation and Exception Management": {
    problemStatement: "Post-trade reconciliation is manual, fragmented, and error-prone. Leads to delayed settlements and exception backlogs.",
    idea: {
      opportunity: "Enable automated reconciliation with predictive exception handling. Reduce manual handoffs and improve post-trade integrity.",
      personas: "Operations Analyst (Middle Office), Reconciliation / Settlement Team",
      scope: "Trade reconciliation (matching & validation), Exception detection & clustering, Resolution & settlement tracking.",
      approach: "Agentic orchestration of reconciliation workflow: Match trades across systems → Detect anomalies / exceptions → Cluster similar issues & predict resolution → Auto-trigger corrective actions. Learning system improves with past resolutions."
    },
    specializedAgents: [
      "Matching Agent – Matches trade records across systems",
      "Exception Detection Agent – Identifies mismatches & errors",
      "Clustering Agent – Groups similar exceptions",
      "Resolution Agent – Suggests / executes corrective actions",
      "Learning Agent – Improves decisions using past cases"
    ],
    benefits: [
      "Faster trade settlement",
      "Improved operational efficiency",
      "Reduced manual reconciliation effort",
      "Faster exception resolution",
      "Improved accuracy & reduced settlement risk",
      "Consistent, auditable workflows"
    ],
    demonstration: [
      "Step 1: Trade data ingested from multiple systems",
      "Step 2: AI matches records automatically",
      "Step 3: Exceptions identified & clustered",
      "Step 4: Resolution recommendations generated",
      "Step 5: Automated / assisted corrective actions executed",
      "Step 6: Final reconciliation & settlement completed"
    ]
  },
  "Synthetic Data Generation": {
    problemStatement: "Fraud datasets are limited and imbalanced. Leads to ineffective AML / fraud detection models.",
    idea: {
      opportunity: "Generate high-quality synthetic data at scale. Improve ML model accuracy for fraud detection.",
      personas: "Fraud Risk Analyst, Data Scientist / ML Engineer",
      scope: "Synthetic financial data generation, Fraud scenario simulation, Model training dataset enrichment.",
      approach: "Agentic synthetic data generation framework: Analyze real transaction patterns → Generate realistic synthetic datasets → Enrich fraud scenarios (rare events) → Feed into ML model training. Enhances model performance without real data dependency."
    },
    specializedAgents: [
      "Data Analysis Agent – Learns patterns from real datasets",
      "Synthetic Data Generation Agent – Creates realistic datasets",
      "Fraud Simulation Agent – Injects fraud scenarios",
      "Validation Agent – Ensures data quality & compliance",
      "Training Agent – Prepares datasets for ML models"
    ],
    benefits: [
      "Stronger fraud detection capabilities",
      "Faster deployment of ML models",
      "Eliminates dependency on limited real data",
      "Scalable data generation",
      "Safer data usage (no PII exposure)",
      "Better detection of evolving fraud patterns"
    ],
    demonstration: [
      "Step 1: Real transaction data analyzed",
      "Step 2: Synthetic dataset generated",
      "Step 3: Fraud scenarios injected",
      "Step 4: Dataset validated for quality",
      "Step 5: Data used to train ML models",
      "Step 6: Improved fraud detection outcomes"
    ]
  },
  "Unified Servicing AI": {
    problemStatement: "Mortgage servicing has become operationally fragmented. Servicers are forced to build and maintain numerous tools outside their Loan Origination System (LOS) to run day-to-day operations — spanning contact centre, back office, and reporting. This creates poor user experience, high cost of operations, cluttered data views, limited analytics capability, and low feasibility for process transformation at scale.",
    idea: {
      opportunity: "Mortgage servicers can consolidate fragmented tooling, eliminate manual workarounds, reduce agent handle time, and operationalise data analytics as a day-to-day capability rather than an ad hoc project. The platform is applicable across servicer types — banks, non-bank servicers, and BPO operations — and scales across high-volume servicing portfolios.",
      personas: "Contact Centre Agent, Back Office Servicing Associate, Operations Manager / Team Lead, Compliance & Policy Officer, Data Analyst / Reporting Lead",
      scope: "Unified contact centre view integrating telephony (NICE, RingCentral) and servicing platforms; real-time speech-to-text with GenAI-guided next best action; back-office single-window operations view by department and user profile; embedded policy and regulatory guidance; inbuilt scripting and VBA automation; role-based persona dashboards with Power BI analytics; SLA tracking, agent performance reporting, and inventory ageing; full mortgage servicing lifecycle coverage — onboarding to foreclosure/payoff."
     },
    specializedAgents: [
      "Speech-to-Text Transcription Agent – Real-time call transcription feeding context into the GenAI guidance layer",
      "Next Best Action Agent – Suggests optimal resolution steps based on live conversation and loan data",
      "Policy & Compliance Guidance Agent – Surfaces relevant regulatory and policy rules at each process step",
      "Call Summarisation Agent – Auto-generates call transfer summaries, eliminating manual note-taking",
      "Back Office Automation Agent – Executes inbuilt scripts and VBA automations for repetitive processing tasks",
      "Notation & Documentation Agent – Auto-generates notations and screen dumps for audit and compliance trails",
      "Analytics & Reporting Agent – Powers persona-based dashboards, SLA tracking, and auto-generated MIS reports",
      "Case Routing & Assignment Agent – Smart case assignment based on agent profile, expertise, and SLA priority"
    ],
    benefits: [
      "Unified operations: one platform replaces multiple siloed tools across contact centre and back office",
      "Reduced AHT: real-time GenAI guidance cuts handle time and agent ramp-up effort",
      "Process accuracy: embedded policy rules and compliance checklists drive 99%+ accuracy",
      "Analytics on demand: Power BI dashboards replace manual reporting; data-driven decisions daily",
      "Cost reduction: eliminates tool sprawl and reduces operational overhead",
      "Faster transformation: inbuilt automation scripting accelerates process change without IT dependency"
    ],
    demonstration: [
      "Step 1: A contact centre agent receives a borrower call → speech-to-text activates in real time",
      "Step 2: GenAI surfaces relevant loan data and suggests the next best action",
      "Step 3: A call summary is auto-generated on transfer",
      "Step 4: Back-office view — a servicing associate processes a task within a single consolidated screen with policy guidance embedded",
      "Step 5: Operations manager view shows live dashboards with agent performance, inventory ageing, and SLA adherence — all without leaving the platform"
    ]
  },
  "Credit Decisioning AI": {
    problemStatement: "Credit underwriting for commercial loans is slow, manual, and error-prone. Underwriters must review large, complex financial documents across multiple formats, extract key ratios, benchmark peers, and calculate risk ratings — all manually. This leads to longer loan approval cycles, inconsistent decisioning quality, and difficulty scaling during high-volume periods.",
    idea: {
      opportunity: "Banks and financial institutions can compress commercial loan approval timelines significantly, reduce manual underwriting effort by ~30%, improve decision consistency, and scale credit operations without proportional headcount growth. The solution is reusable across loan products and geographies.",
      personas: "Loan Underwriter, Credit Officer, Credit Risk Manager, Loan Processor",
      scope: "Ingestion of financial documents (balance sheets, P&L, cash flow statements) in multiple formats; LLM-based data extraction and field mapping to credit analysis templates; automated financial ratio calculation (DTI, leverage, liquidity, coverage); risk rating generation; peer comparison, vertical/horizontal analysis, and industry benchmarking; summarisation and credit decision recommendation; synthetic test data creation; RAG (Retrieval-Augmented Generation) using LangChain + VectorDB."
     },
    specializedAgents: [
      "Document Ingestion Agent – Classifies and ingests financial documents across formats",
      "Data Extraction & Mapping Agent – LLM-driven extraction of financial fields into structured templates",
      "Financial Analysis Agent – Calculates ratios (DTI, leverage, liquidity, coverage); runs vertical/horizontal analysis",
      "Peer Benchmarking Agent – Compares borrower financials against industry peers and benchmarks",
      "Risk Rating Agent – Generates a composite credit/risk score based on ratio thresholds and model logic",
      "Summarisation & Recommendation Agent – Produces a credit decision narrative with reasoning and source references",
      "Synthetic Data Creation Engine – Generates training data at scale from smaller real-data samples",
      "RAG Layer (LangChain + VectorDB) – Retrieves contextually relevant financial content to ground LLM outputs"
    ],
    benefits: [
      "Faster loan approvals: reduced cycle time through automated extraction and analysis",
      "Operational efficiency: ~30% improvement in underwriting productivity",
      "Decision quality: data-driven risk ratings with consistent methodology",
      "Fraud detection: AI flags anomalies and inconsistencies in financial data",
      "Reusability: parameterised prompts and reusable artefacts across loan types",
      "Scalability: handles high-volume periods without additional FTEs"
    ],
    demonstration: [
      "Step 1: Financial documents are uploaded",
      "Step 2: The LLM extracts and maps data fields",
      "Step 3: Key ratios are calculated automatically",
      "Step 4: Risk rating is generated with supporting reasoning",
      "Step 5: A peer comparison and industry benchmark view is displayed",
      "Step 6: A credit decision summary with recommendation is produced — enabling the underwriter to review, validate, and approve in a fraction of the traditional cycle time"
    ]
  },
  "Digital Automation Fabric (DAF)": {
    problemStatement: "Mortgage and property record operations involve processing millions of unstructured documents across 250+ sub-document types from 3,000 counties. Manual data capture results in poor accuracy, high operational costs, low straight-through processing (STP) rates, and inability to scale with volume spikes.",
    idea: {
      opportunity: "Banks, mortgage servicers, and property data providers can eliminate manual bottlenecks in document-intensive workflows, drive 99.5%+ accuracy, improve STP by 50%, and reduce per-record processing costs significantly — while scaling to handle 4.6 million+ records per month without adding headcount.",
      personas: "Mortgage Operations Manager, Loan Underwriter / Credit Officer, Chief Data Officer / Head of Ops Technology, Compliance & QC Lead",
      scope: "Multi-format document ingestion (250+ sub-document types, 3,000 US counties); OCR and ML-based document classification and indexing; automated data extraction and entry/verification; APN (Assessor Parcel Number) research automation; digital QC and quality audit workflows; output file generation with reject and edit handling; end-to-end process orchestration with persona-driven dashboards; BPaaS delivery — hosted platform (DIF) + managed operations."
     },
    specializedAgents: [
      "OCR Engine – Converts document images to machine-readable text across all formats",
      "ML Classification Agent – Recognises and indexes 250+ document sub-types automatically",
      "Data Extraction Agent – Extracts structured data points from unstructured content",
      "APN Research Agent – Automates Assessor Parcel Number lookup and validation",
      "Digital QC Agent – Performs automated quality checks and flags exceptions",
      "Quality Audit Module – Validates output against standards; manages rejects and edits",
      "RPA Automation Layer – Handles repetitive data entry, verification, and output file generation",
      "Insights & Dashboard Agent – Delivers persona-driven operational analytics and SLA visibility"
    ],
    benefits: [
      "Accuracy: 99.5% data accuracy achieved",
      "STP improvement: 50% improvement in straight-through processing for unstructured mortgage documents",
      "Productivity: 30–40% productivity improvement",
      "Scale: 4.6 million records processed per month",
      "Cost optimisation: vendor consolidation reduces tech and ops overhead"
    ],
    demonstration: [
      "Step 1: Mortgage documents in multiple formats are ingested",
      "Step 2: Documents are classified into 250+ document types",
      "Step 3: Data is extracted with 99.5% accuracy",
      "Step 4: APN research is completed automatically",
      "Step 5: Digital QC validates output",
      "Step 6: Clean structured data files are generated",
      "Step 7: Operational dashboards display throughput, accuracy, and SLA metrics in real time — eliminating manual data capture entirely"
    ]
  },
  "AI-Powered Feedback Loop Closure": {
    technology: "Azure",
    problemStatement: "Banks handle massive volumes of unstructured customer feedback across portals, surveys, app stores, and social media. Manual triage leads to delayed resolutions, generic responses, and underutilized insights — eroding client satisfaction and increasing operational overhead.",
    idea: {
      opportunity: "Banks can transform reactive feedback handling into a proactive, insight-driven process. Automated triage, ticket creation, and follow-up reduce resolution time, improve NPS, and free relationship managers to focus on high-value interactions.",
      personas: "Digital Banking Product Owners, AI & Analytics Leaders, RMs, IT Service Management Leads",
      scope: "Feedback ingestion from surveys, banking portals, app stores, and social media; automated classification (Business/IT, Complaints/Issues/Suggestions) and sentiment analysis; history similarity check using vector embeddings; automated actions — JIRA ticket creation, ServiceNow incident creation, customer acknowledgement; RM and user dashboards with feedback and process analytics; proactive follow-up and loop closure notifications."
    },
    specializedAgents: [
      "Pre-Processing Unit Agent",
      "Data Processing Unit Agent / Orchestrator",
      "History Processing Agent",
      "Action Steps Agent",
      "Monitoring Layer Agent",
      "Notification Control Unit"
    ],
    benefits: [
      "Faster resolution",
      "Proactive issue management",
      "Personalised engagement",
      "Operational efficiency",
      "Scalability"
    ],
    demonstration: [
      "Step 1: A customer submits feedback via a banking portal",
      "Step 2: The system classifies the feedback and analyses sentiment",
      "Step 3: A history check identifies a similar past issue",
      "Step 4: A ServiceNow ticket is auto-created and assigned",
      "Step 5: The RM is notified on their dashboard",
      "Step 6: The customer receives a personalised acknowledgement, closing the loop automatically"
    ]
  },
  "GNN-Based AML Transaction Monitoring": {
    technology: "GNN (GraphSAGE + GAT) · Kafka · Claude API (roadmap)",
    problemStatement: "Traditional AML transaction monitoring systems evaluate transactions one at a time against fixed, rule-based thresholds. This approach generates excessive false positives (typical precision of ~5%), misses network-level laundering patterns like smurfing, layering, and shell company chains, and buries investigators under unranked alert queues. Criminal networks exploit the gaps between transactions that rule-based systems cannot see.",
    idea: {
      opportunity: "Banks can reduce investigator workload from reviewing thousands of unranked alerts to a prioritised queue where 9 in 10 top-ranked accounts are genuine laundering cases. The GNN architecture detects cross-account crime patterns invisible to rule-based systems, improves SAR filing accuracy, and lays the foundation for an LLM narrative layer that cuts SAR drafting from 2–3 hours to 5 minutes per case.",
      personas: "AML Investigator, Financial Intelligence Unit Lead, Chief Compliance Officer, Financial Crime Data Scientist, SAR Filing Officer",
      scope: "Ingestion of transactions, KYC/CDD, sanctions/PEP data, and corporate ownership structures via Kafka event stream; knowledge graph construction across 12 entity node types (Person, Account, Transaction, Company, Address, Device/IP, Financial Institution, PEP, Sanctioned Entity, Asset, Alert/SAR, Country/Jurisdiction); GNN model training (GraphSAGE + GAT) for account-level risk scoring; detection of 5 laundering typologies (smurfing, fan-out layering, round-tripping, scatter-gather, shell company chains); ranked alert output with risk tiers (Critical 80–100, High 60–80, Medium 30–60, Low 0–30); layered investigator views (macro heatmap, embedding clusters via UMAP, ego network, alert queue, pattern filter); LLM narrative layer (roadmap) for automated SAR drafting via Claude API; 3-phase roadmap from POC to production."
    },
    specializedAgents: [
      "GraphSAGE Agent – Aggregates 1-hop and 2-hop neighbourhood transaction features per account",
      "GAT (Graph Attention) Agent – Learns which account connections carry the highest risk signal using 4 attention heads",
      "Community Detection Module – Louvain/SCAN algorithms identify laundering clusters and money mule rings",
      "Link Prediction Module – Surfaces hidden relationships between entities not directly connected",
      "Path Analysis Module – Traces layering chains and mule routing across multi-hop transaction paths",
      "Embedding Visualiser (UMAP) – Projects 512-dimension GNN embeddings to 2D for investigator cluster exploration",
      "Alert Ranking Engine – Scores all accounts simultaneously; outputs a tiered risk queue (Critical/High/Medium/Low)",
      "LLM SAR Narrative Agent (roadmap) – Connects GNN alert output to Claude API to auto-generate formal SAR narratives",
      "Temporal GNN Module (roadmap) – EvolveGCN/TGN for detecting dormant-to-active behavioural anomalies over time",
      "Federated Learning Layer (roadmap) – Cross-institution model training on private data to detect inter-bank laundering networks"
    ],
    benefits: [
      "Detection quality: 76% ROC-AUC, 70% recall on an untuned POC — 9 of 10 top alerts are genuine",
      "Precision improvement: 49% precision vs ~5% for typical rule-based systems — 10× better signal",
      "Investigator efficiency: reduces the review queue to 960 critical accounts from 5,000 total",
      "Speed: full model trained in 144 seconds on a standard CPU — no GPU required",
      "SAR drafting (roadmap): LLM layer cuts SAR narrative drafting from 2–3 hours to 5 minutes",
      "Typology coverage: 5 criminal patterns detected simultaneously; extensible to new typologies",
      "Network intelligence: detects cross-account laundering rings invisible to single-transaction rules"
    ],
    demonstration: [
      "Step 1: The live POC dashboard runs the full pipeline on 100,000 synthetic transactions across 5,000 accounts",
      "Step 2: The GNN trains in 144 seconds on a laptop CPU; 1,567 laundering accounts are scored",
      "Step 3: The top alert queue shows 9 of 10 highest-scored accounts are genuine laundering cases",
      "Step 4: The interactive knowledge graph lets investigators drill from macro heatmap → cluster view → ego network for any suspect account",
      "Step 5: 5 typology patterns (smurfing, fan-out layering, round-tripping, scatter-gather, shell company chain) are visually traced",
      "Step 6: The roadmap highlights GNN + Claude API SAR narrative integration as the highest-impact next step — reducing a 3-hour task to 5 minutes",
      "POC metrics: 100,000 transactions processed · 5,000 accounts scored · 1,567 laundering accounts · 76% ROC-AUC · 70% recall · 58% F1 · 144s CPU training · 9/10 top-10 alert accuracy"
    ]
  }
};

// Define solutions for each category
export const CATEGORY_SOLUTIONS = {
  "retail-banking": {
    title: "Retail Banking",
    solutions: [
      {
        title: "Real Time Loan Application Fraud Detection",
        description: "",
        image: "rb01.jpg",
        demoLink: "http://real-time-app-revamped-640237069320-us-west-2-an.s3-website-us-west-2.amazonaws.com/"
      },
      {
        title: "AI Powered Smart Fund Lending Platform",
        description: "",
        image: "rb02.png"
      },
      {
        title: "Unified Servicing AI",
        description: "",
        image: "rb02.png",
        link: "https://cognizantonline.sharepoint.com/:v:/r/sites/BFSILabCognizant/Shared%20Documents/BFSI%20Use%20cases/SL%20Use%20cases%20for%20website/IOA-%20BFS%20use%20cases/Unified%20Servicing%20Ai-V9.m4v?csf=1&web=1&e=xRx3Vb&referrer=Outlook.Win32&referrerScenario=email-linkwithembed"
      }
    ]
  },
  "lending-mortgages": {
    title: "Retail Banking",
    solutions: [
      {
        title: "Real Time Loan Application Fraud Detection",
        description: "",
        image: "rb01.jpg",
        demoLink: "http://real-time-app-revamped-640237069320-us-west-2-an.s3-website-us-west-2.amazonaws.com/"
      },
      {
        title: "AI Powered Smart Fund Lending Platform",
        description: "",
        image: "rb02.png"
      }
    ]
  },
  "kyc-aml-fraud": {
    title: "Retail Banking",
    solutions: [
      {
        title: "KYC Processing",
        description: "",
        image: "Orchestrating Seamless Compliance via Autonomous Agentic KYC Transformation.jpeg",
        link: "https://cognizantonline-my.sharepoint.com/personal/113135_cognizant_com/_layouts/15/stream.aspx?id=%2Fpersonal%2F113135%5Fcognizant%5Fcom%2FDocuments%2FDocuments%2FC%20Drive%2FFramework%20Tools%20%26%20Accelerators%2FAgentic%20AI%2FAgents%20Foundry%2FSolution%20Demo%2F33%2E%20Agentic%20Solution%20%2D%20KYC%20Processes%2FAutomated%20KYC%20Processes%2Emp4&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2E1a029402%2D1670%2D4d4c%2D9641%2D03ecb9a6eaa0"
      }
    ]
  },
  "commercial-banking": {
    title: "Commercial Banking",
    solutions: [
      {
        title: "Real Time Loan Application Fraud Detection",
        description: "",
        image: "cb01.jpg",
        demoLink: "http://real-time-app-revamped-640237069320-us-west-2-an.s3-website-us-west-2.amazonaws.com/"
      },
      {
        title: "AI Powered Smart Fund Lending Platform",
        description: "",
        image: "cb02.png"
      },
      {
        title: "Commercial Banking - Client Onboarding - Compliance Checks",
        description: "",
        image: "Intelligent Automation Corporate Banking Next-Gen KYB through Agentic AI.jpeg",
        link: "https://cognizantonline-my.sharepoint.com/personal/113135_cognizant_com/_layouts/15/stream.aspx?id=%2Fpersonal%2F113135%5Fcognizant%5Fcom%2FDocuments%2FDocuments%2FC%20Drive%2FFramework%20Tools%20%26%20Accelerators%2FAgentic%20AI%2FAgents%20Foundry%2FSolution%20Demo%2F13%2E%20Commercial%20Banking%20%2D%20Client%20Onboarding%2F13%5FCommercial%20Banking%5FClient%20Onboarding%2Emp4&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2Ef3fa911b%2D152a%2D4773%2D8283%2Dfa6cd2867354"
      }
    ]
  },
  "investment-banking": {
    title: "Investment Banking",
    solutions: [
      {
        title: "Real Time Loan Application Fraud Detection",
        description: "",
        image: "ib01.jpg",
        demoLink: "http://real-time-app-revamped-640237069320-us-west-2-an.s3-website-us-west-2.amazonaws.com/"
      },
      {
        title: "AI Powered Smart Fund Lending Platform",
        description: "",
        image: "ib02.png"
      }
    ]
  },
  "cards-payments": {
    title: "Cards & Payments",
    solutions: [
      {
        title: "Credit card transaction fraud detection agent",
        description: "",
        image: "cap02.png",
        demoLink: "http://creditcard-facelift-version.s3-website-us-west-2.amazonaws.com/"
      },
      {
        title: "Fraud and Dispute Management",
        description: "",
        image: "Transforming Fraud and Dispute Resolution Through Agentic Intelligence.jpeg",
        link: "https://cognizantonline-my.sharepoint.com/:v:/r/personal/113135_cognizant_com/Documents/Documents/C%20Drive/Framework%20Tools%20%26%20Accelerators/Agentic%20AI/Agents%20Foundry/Solution%20Demo/34.%20Agentic%20Solution%20-%20Fraud%20%26%20Dispute%20Management/Fraud%20and%20Dispute%20Management.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=ZSexnD"
      },
      {
        title: "Invisible Payment Solution",
        description: "",
        image: "InvisiblePaymentSolutions.png",
        demoLink: "https://20.219.97.165.nip.io/login/",
        link: "https://cognizantonline-my.sharepoint.com/:v:/r/personal/2101809_cognizant_com/Documents/Microsoft%20Teams%20Chat%20Files/SmartPay_Shopping_App_Demo.mp4?csf=1&web=1&e=xQe3fE&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D"
      }
    ]
  },
  "risk-compliance": {
    title: "Risk & Compliance",
    solutions: [
      {
        title: "Credit card transaction fraud detection agent",
        description: "",
        image: "rac01.png",
        demoLink: "http://creditcard-facelift-version.s3-website-us-west-2.amazonaws.com/"
      },
      {
        title: "AML SAR Generation Workflow - Agentic AI",
        description: "",
        image: "rac02.png",
        demoLink: "http://sar-facelift.s3-website-us-west-2.amazonaws.com/"
      },
      {
        title: "AI-Driven document analysis and generation solution - Agentic AI",
        description: "",
        image: "rac03.png",
        demoLink: "https://mg8mkgmzhp.us-west-2.awsapprunner.com/"
      }
    ]
  },
  "asset-wealth-management": {
    title: "Asset and Wealth Management",
    solutions: [
      {
        title: "AI enabled Investment Advisory and Portfolio construction and balancing - Agentic AI",
        description: "",
        image: "awm01.png",
        demoLink: "https://azure-advisor-app.greenwater-842e0658.eastus2.azurecontainerapps.io/"
      },
      {
        title: "Common Domain Model",
        description: "",
        image: "awm02.png",
        demoLink: "https://hk9pjj82vm.us-west-2.awsapprunner.com/signin"
      },
      {
        title: "Portfolio Rebalancing",
        description: "",
        image: "Next-Gen Agentic Engine for Context-Aware HNW Portfolio Optimization.jpeg",
        link: "https://cognizantonline-my.sharepoint.com/:v:/r/personal/113135_cognizant_com/Documents/Documents/C%20Drive/Framework%20Tools%20%26%20Accelerators/Agentic%20AI/Agents%20Foundry/Solution%20Demo/01.%20Portfolio%20Rebalancing/Portfolio%20Rebalancing%20-%20Demo.mp4?csf=1&web=1&e=nryu2A&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D"
      },
      {
        title: "User Personalization for Asset & Wealth Management",
        description: "",
        image: "Driving Hyper-Personalized Wealth Journeys via Autonomous Agents.jpeg",
        link: "https://cognizantonline-my.sharepoint.com/:v:/r/personal/113135_cognizant_com/Documents/Documents/C%20Drive/Framework%20Tools%20%26%20Accelerators/Agentic%20AI/Agents%20Foundry/Solution%20Demo/22.%20Vibe%20Coding_User%20Personalization%20Solution/Vibe%20Coding%20User%20Personalization%20Demo%20Final%20-%20Video%20(1).mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=kvI41K"
      },
      {
        title: "Portfolio Exception Monitor",
        description: "",
        image: "Proactive Portfolio Resilience with Agentic Exception Monitoring.jpeg",
        link: "https://cognizantonline-my.sharepoint.com/:v:/r/personal/113135_cognizant_com/Documents/Documents/C%20Drive/Framework%20Tools%20%26%20Accelerators/Agentic%20AI/Agents%20Foundry/Solution%20Demo/23.%20Vibe%20Coding_Portfolio%20Exception%20Monitor/23_Demo%20Video_Vibe%20Coding_Portfolio%20Exception%20Monitor_Rajdeep.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=YaJK74"
      },
      {
        title: "Wealth Management - Life Stage Simulator (POV: Clients and Financial Advisor)",
        description: "",
        image: "Empowering Financial Preparedness Through Agentic Goal Modeling.jpeg",
        link: "https://cognizantonline-my.sharepoint.com/:v:/r/personal/113135_cognizant_com/Documents/Documents/C%20Drive/Framework%20Tools%20%26%20Accelerators/Agentic%20AI/Agents%20Foundry/Solution%20Demo/24.%20Wealth%20Management%20Life%20Stage%20Simulator/WM_Life%20Stage%20Simulator.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=S2a38l"
      }
    ]
  },
  "awm-portfolio-construction": {
    title: "Asset and Wealth Management",
    solutions: [
      {
        title: "AI enabled Investment Advisory and Portfolio construction and balancing - Agentic AI",
        description: "",
        image: "awm01.png",
        demoLink: "https://azure-advisor-app.greenwater-842e0658.eastus2.azurecontainerapps.io/"
      }
    ]
  },
  "awm-portfolio-mgmt": {
    title: "Asset and Wealth Management",
    solutions: [
      {
        title: "Portfolio Rebalancing",
        description: "",
        image: "Next-Gen Agentic Engine for Context-Aware HNW Portfolio Optimization.jpeg",
        link: "https://cognizantonline-my.sharepoint.com/:v:/r/personal/113135_cognizant_com/Documents/Documents/C%20Drive/Framework%20Tools%20%26%20Accelerators/Agentic%20AI/Agents%20Foundry/Solution%20Demo/01.%20Portfolio%20Rebalancing/Portfolio%20Rebalancing%20-%20Demo.mp4?csf=1&web=1&e=nryu2A&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D"
      }
    ]
  },
  "awm-lead-generation": {
    title: "Asset and Wealth Management",
    solutions: [
      {
        title: "Wealth Management - Life Stage Simulator (POV: Clients and Financial Advisor)",
        description: "",
        image: "Empowering Financial Preparedness Through Agentic Goal Modeling.jpeg",
        link: "https://cognizantonline-my.sharepoint.com/:v:/r/personal/113135_cognizant_com/Documents/Documents/C%20Drive/Framework%20Tools%20%26%20Accelerators/Agentic%20AI/Agents%20Foundry/Solution%20Demo/24.%20Wealth%20Management%20Life%20Stage%20Simulator/WM_Life%20Stage%20Simulator.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=S2a38l"
      }
    ]
  },
  "awm-model-management": {
    title: "Asset and Wealth Management",
    solutions: [
      {
        title: "Common Domain Model",
        description: "",
        image: "awm02.png",
        demoLink: "https://hk9pjj82vm.us-west-2.awsapprunner.com/signin"
      }
    ]
  },
  "awm-portfolio-accounting": {
    title: "Asset and Wealth Management",
    solutions: [
      {
        title: "User Personalization for Asset & Wealth Management",
        description: "",
        image: "Driving Hyper-Personalized Wealth Journeys via Autonomous Agents.jpeg",
        link: "https://cognizantonline-my.sharepoint.com/:v:/r/personal/113135_cognizant_com/Documents/Documents/C%20Drive/Framework%20Tools%20%26%20Accelerators/Agentic%20AI/Agents%20Foundry/Solution%20Demo/22.%20Vibe%20Coding_User%20Personalization%20Solution/Vibe%20Coding%20User%20Personalization%20Demo%20Final%20-%20Video%20(1).mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=kvI41K"
      }
    ]
  },
  "awm-regulatory-reporting": {
    title: "Asset and Wealth Management",
    solutions: [
      {
        title: "Portfolio Exception Monitor",
        description: "",
        image: "Proactive Portfolio Resilience with Agentic Exception Monitoring.jpeg",
        link: "https://cognizantonline-my.sharepoint.com/:v:/r/personal/113135_cognizant_com/Documents/Documents/C%20Drive/Framework%20Tools%20%26%20Accelerators/Agentic%20AI/Agents%20Foundry/Solution%20Demo/23.%20Vibe%20Coding_Portfolio%20Exception%20Monitor/23_Demo%20Video_Vibe%20Coding_Portfolio%20Exception%20Monitor_Rajdeep.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=YaJK74"
      }
    ]
  },
  "capital-market": {
    title: "Capital Market",
    solutions: [
      {
        title: "Trade Reconciliation and Exception Management",
        description: "",
        image: "Transforming Post-Trade Integrity Through Agentic Reconciliation Orchestration.jpeg",
        link: "https://cognizantonline-my.sharepoint.com/:v:/r/personal/113135_cognizant_com/Documents/Documents/C%20Drive/Framework%20Tools%20%26%20Accelerators/Agentic%20AI/Agents%20Foundry/Solution%20Demo/43%20Trade%20Reconciliation%20and%20Exception%20Management/Trade%20Reconciliation%20and%20Exception%20Management.mp4?csf=1&web=1&e=Vrs3F7&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D"
      }
    ]
  },
  "data-management": {
    title: "Data Management",
    solutions: [
      {
        title: "Synthetic Data Generation",
        description: "",
        image: "Empowering Advanced Fraud Detection via Automated Synthetic Data Generation.jpeg",
        link: "https://cognizantonline-my.sharepoint.com/:v:/r/personal/113135_cognizant_com/Documents/Documents/C%20Drive/Framework%20Tools%20%26%20Accelerators/Agentic%20AI/Agents%20Foundry/Solution%20Demo/46.%20Synthetic%20Data%20Generation/Synthetic%20Data%20Generation%20for%20Fraud%20Detection%20Demo.mp4?csf=1&web=1&e=KhxC5S&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D"
      }
    ]
  },
  "cb-clm-onboarding": {
    title: "Commercial Banking",
    solutions: [
      {
        title: "Commercial Banking - Client Onboarding - Compliance Checks",
        description: "",
        image: "Intelligent Automation Corporate Banking Next-Gen KYB through Agentic AI.jpeg",
        link: "https://cognizantonline-my.sharepoint.com/personal/113135_cognizant_com/_layouts/15/stream.aspx?id=%2Fpersonal%2F113135%5Fcognizant%5Fcom%2FDocuments%2FDocuments%2FC%20Drive%2FFramework%20Tools%20%26%20Accelerators%2FAgentic%20AI%2FAgents%20Foundry%2FSolution%20Demo%2F13%2E%20Commercial%20Banking%20%2D%20Client%20Onboarding%2F13%5FCommercial%20Banking%5FClient%20Onboarding%2Emp4&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2Ef3fa911b%2D152a%2D4773%2D8283%2Dfa6cd2867354"
      }
    ]
  },
  "cap-authorization": {
    title: "Cards & Payments",
    solutions: [
      {
        title: "Invisible Payment Solution",
        description: "",
        image: "InvisiblePaymentSolutions.png",
        demoLink: "https://20.219.97.165.nip.io/login/",
        link: "https://cognizantonline-my.sharepoint.com/:v:/r/personal/2101809_cognizant_com/Documents/Microsoft%20Teams%20Chat%20Files/SmartPay_Shopping_App_Demo.mp4?csf=1&web=1&e=xQe3fE&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D"
      }
    ]
  },
  "cap-txn-monitoring": {
    title: "Cards & Payments",
    solutions: [
      {
        title: "Credit card transaction fraud detection agent",
        description: "",
        image: "cap02.png",
        demoLink: "http://creditcard-facelift-version.s3-website-us-west-2.amazonaws.com/"
      }
    ]
  },
  "cap-case-mgmt": {
    title: "Cards & Payments",
    solutions: [
      {
        title: "Fraud and Dispute Management",
        description: "",
        image: "Transforming Fraud and Dispute Resolution Through Agentic Intelligence.jpeg",
        link: "https://cognizantonline-my.sharepoint.com/:v:/r/personal/113135_cognizant_com/Documents/Documents/C%20Drive/Framework%20Tools%20%26%20Accelerators/Agentic%20AI/Agents%20Foundry/Solution%20Demo/34.%20Agentic%20Solution%20-%20Fraud%20%26%20Dispute%20Management/Fraud%20and%20Dispute%20Management.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=ZSexnD"
      }
    ]
  },
  "rc-fraud-decisioning": {
    title: "Risk & Compliance",
    solutions: [
      {
        title: "Credit card transaction fraud detection agent",
        description: "",
        image: "rac01.png",
        demoLink: "http://creditcard-facelift-version.s3-website-us-west-2.amazonaws.com/"
      }
    ]
  },
  "rc-sar-filing": {
    title: "Risk & Compliance",
    solutions: [
      {
        title: "AML SAR Generation Workflow - Agentic AI",
        description: "",
        image: "rac02.png",
        demoLink: "http://sar-facelift.s3-website-us-west-2.amazonaws.com/"
      }
    ]
  },
  "rc-reg-change": {
    title: "Risk & Compliance",
    solutions: [
      {
        title: "AI-Driven document analysis and generation solution - Agentic AI",
        description: "",
        image: "rac03.png",
        demoLink: "https://mg8mkgmzhp.us-west-2.awsapprunner.com/"
      }
    ]
  },
  "wm-advisor-relationship": {
    title: "Wealth Management",
    solutions: [
      {
        title: "AI enabled Investment Advisory and Portfolio construction and balancing - Agentic AI",
        description: "",
        image: "awm01.png",
        demoLink: "https://azure-advisor-app.greenwater-842e0658.eastus2.azurecontainerapps.io/"
      }
    ]
  },
  "ib-client-analytics": {
    title: "Investment Banking",
    solutions: [
      {
        title: "Common Domain Model",
        description: "",
        image: "awm02.png",
        demoLink: "https://hk9pjj82vm.us-west-2.awsapprunner.com/signin"
      }
    ]
  },
  "wm-account-opening": {
    title: "Wealth Management",
    solutions: [
      {
        title: "User Personalization for Asset & Wealth Management",
        description: "",
        image: "Driving Hyper-Personalized Wealth Journeys via Autonomous Agents.jpeg",
        link: "https://cognizantonline-my.sharepoint.com/:v:/r/personal/113135_cognizant_com/Documents/Documents/C%20Drive/Framework%20Tools%20%26%20Accelerators/Agentic%20AI/Agents%20Foundry/Solution%20Demo/22.%20Vibe%20Coding_User%20Personalization%20Solution/Vibe%20Coding%20User%20Personalization%20Demo%20Final%20-%20Video%20(1).mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=kvI41K"
      },
      {
        title: "Wealth Management - Life Stage Simulator (POV: Clients and Financial Advisor)",
        description: "",
        image: "Empowering Financial Preparedness Through Agentic Goal Modeling.jpeg",
        link: "https://cognizantonline-my.sharepoint.com/:v:/r/personal/113135_cognizant_com/Documents/Documents/C%20Drive/Framework%20Tools%20%26%20Accelerators/Agentic%20AI/Agents%20Foundry/Solution%20Demo/24.%20Wealth%20Management%20Life%20Stage%20Simulator/WM_Life%20Stage%20Simulator.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=S2a38l"
      }
    ]
  },
  "wm-portfolio-risk": {
    title: "Wealth Management",
    solutions: [
      {
        title: "Portfolio Exception Monitor",
        description: "",
        image: "Proactive Portfolio Resilience with Agentic Exception Monitoring.jpeg",
        link: "https://cognizantonline-my.sharepoint.com/:v:/r/personal/113135_cognizant_com/Documents/Documents/C%20Drive/Framework%20Tools%20%26%20Accelerators/Agentic%20AI/Agents%20Foundry/Solution%20Demo/23.%20Vibe%20Coding_Portfolio%20Exception%20Monitor/23_Demo%20Video_Vibe%20Coding_Portfolio%20Exception%20Monitor_Rajdeep.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=YaJK74"
      }
    ]
  },
  "am-account-opening": {
    title: "Asset Management",
    solutions: [
      {
        title: "User Personalization for Asset & Wealth Management",
        description: "",
        image: "Driving Hyper-Personalized Wealth Journeys via Autonomous Agents.jpeg",
        link: "https://cognizantonline-my.sharepoint.com/:v:/r/personal/113135_cognizant_com/Documents/Documents/C%20Drive/Framework%20Tools%20%26%20Accelerators/Agentic%20AI/Agents%20Foundry/Solution%20Demo/22.%20Vibe%20Coding_User%20Personalization%20Solution/Vibe%20Coding%20User%20Personalization%20Demo%20Final%20-%20Video%20(1).mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=kvI41K"
      }
    ]
  },
  "am-trade-recon": {
    title: "Asset Management",
    solutions: [
      {
        title: "Trade Reconciliation and Exception Management",
        description: "",
        image: "Transforming Post-Trade Integrity Through Agentic Reconciliation Orchestration.jpeg",
        link: "https://cognizantonline-my.sharepoint.com/:v:/r/personal/113135_cognizant_com/Documents/Documents/C%20Drive/Framework%20Tools%20%26%20Accelerators/Agentic%20AI/Agents%20Foundry/Solution%20Demo/43%20Trade%20Reconciliation%20and%20Exception%20Management/Trade%20Reconciliation%20and%20Exception%20Management.mp4?csf=1&web=1&e=Vrs3F7&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D"
      }
    ]
  },
  "mi-data-analytics": {
    title: "Market Infrastructure",
    solutions: [
      {
        title: "Synthetic Data Generation",
        description: "",
        image: "Empowering Advanced Fraud Detection via Automated Synthetic Data Generation.jpeg",
        link: "https://cognizantonline-my.sharepoint.com/:v:/r/personal/113135_cognizant_com/Documents/Documents/C%20Drive/Framework%20Tools%20%26%20Accelerators/Agentic%20AI/Agents%20Foundry/Solution%20Demo/46.%20Synthetic%20Data%20Generation/Synthetic%20Data%20Generation%20for%20Fraud%20Detection%20Demo.mp4?csf=1&web=1&e=KhxC5S&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D"
      }
    ]
  },
  "cb-loan-origination": {
    title: "Commercial Banking",
    solutions: [
      {
        title: "Credit Decisioning AI",
        description: "",
        image: "cb01.jpg",
        link: "https://cognizantonline.sharepoint.com/:v:/r/sites/BFSILabCognizant/Shared%20Documents/BFSI%20Use%20cases/SL%20Use%20cases%20for%20website/IOA-%20BFS%20use%20cases/Credit%20Decisioning.mp4?csf=1&web=1&e=AoGJ8U&referrer=Outlook.Win32&referrerScenario=email-linkwithembed"
      }
    ]
  },
  "cb-loan-servicing": {
    title: "Commercial Banking",
    solutions: [
      {
        title: "Digital Automation Fabric (DAF)",
        description: "",
        image: "cb02.png",
        link: "https://cognizantonline.sharepoint.com/:v:/r/sites/BFSILabCognizant/Shared%20Documents/BFSI%20Use%20cases/SL%20Use%20cases%20for%20website/IOA-%20BFS%20use%20cases/Digital%20Automation%20Fabric_2025.mp4?csf=1&web=1&e=Qygbdh&referrer=Outlook.Win32&referrerScenario=email-linkwithembed"
      }
    ]
  },
  "rb-client-reporting": {
    title: "Retail Banking",
    solutions: [
      {
        title: "AI-Powered Feedback Loop Closure",
        description: "",
        image: "rb02.png",
        link: "https://cognizantonline.sharepoint.com/:v:/r/sites/BFSILabCognizant/Shared%20Documents/BFSI%20Use%20cases/Detailed%20use%20cases/Feedback%20loop/Demo_4_2%201.mp4?csf=1&web=1&e=umUBgd&referrer=Outlook.Win32&referrerScenario=email-linkwithembed"
      }
    ]
  },
  "rc-transaction-screening": {
    title: "Risk & Compliance",
    solutions: [
      {
        title: "GNN-Based AML Transaction Monitoring",
        description: "",
        image: "rac02.png",
        link: "https://cognizantonline.sharepoint.com/:v:/r/sites/BFSILabCognizant/Shared%20Documents/BFSI%20Use%20cases/Detailed%20use%20cases/Graph%20Neural%20Network%20based%20%20AML/GNN%20based%20Transaction%20monitoring-20260609_210802-Meeting%20Recording.mp4?csf=1&web=1&e=9xGUsN&referrer=Outlook.Win32&referrerScenario=email-linkwithembed"
      }
    ]
  }
};

export default function CategorySolutionsPage() {
  const { category } = useParams();
  const location = useLocation();
  const navigate = useNavigate();
  const categoryData = CATEGORY_SOLUTIONS[category];
  const headingLabel = location.state?.fromLabel || categoryData?.title;
  const [selectedSolution, setSelectedSolution] = useState(null);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isCasestudyView, setIsCasestudyView] = useState(false);

  const handleCardClick = (solution) => {
    const solutionDetails = SOLUTION_DETAILS[solution.title];
    if (solutionDetails) {
      setSelectedSolution({
        title: solution.title,
        description: solution.description,
        link: solution.link || null,
        demoLink: solution.demoLink || null,
        ...solutionDetails
      });
      setIsCasestudyView(false);
      setIsModalOpen(true);
    }
  };

  const handleCloseModal = () => {
    setIsModalOpen(false);
    setIsCasestudyView(false);
    setTimeout(() => setSelectedSolution(null), 300);
  };

  const hasCasestudyContent = Boolean(
    selectedSolution?.idea &&
    typeof selectedSolution.idea === "object" &&
    !Array.isArray(selectedSolution.idea)
  );

  // If category not found, show error
  if (!categoryData) {
    return (
      <div className="w-full">
        <TopHeader />
        <DarkMarketplaceNav />
        <section className="w-full bg-white py-[60px]">
          <PageContainer>
            <h2 className="text-[#00005A] font-bold text-[32px] leading-[36px]">
              Category not found
            </h2>
          </PageContainer>
        </section>
        <Footer />
      </div>
    );
  }

  return (
    <div className="w-full">
      <TopHeader />
      <DarkMarketplaceNav />
      <section className="w-full bg-white py-[60px]">
        <PageContainer>
          <div className="mb-[40px] inline-block">
            <h2
              className="text-[#00005A] font-bold text-[22px] leading-[26px] mb-[8px] cursor-pointer hover:opacity-80"
              onClick={() => navigate(-1)}
            >
              {headingLabel}
            </h2>
          </div>

          {/* Solutions Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-[32px]">
            {categoryData.solutions.map((solution, index) => (
              <div
                key={index}
                className="border border-[#D0D0CE] bg-white overflow-hidden hover:shadow-lg transition-shadow cursor-pointer rounded-[8px]"
                onClick={() => handleCardClick(solution)}
              >
                {/* Image Container */}
                <div className="w-full h-[200px] bg-gradient-to-br from-[#001F54] to-[#003D8F] flex items-center justify-center overflow-hidden">
                  <img
                    src={`/assets/images/${solution.image}`}
                    alt={solution.title}
                    className="w-full h-full object-cover"
                  />
                </div>

                {/* Content */}
                <div className="p-[24px]">
                  <h3 className="text-[#5B9BD5] font-semibold text-[18px] leading-[22px] hover:underline cursor-pointer">
                    {solution.title}
                  </h3>
                </div>
              </div>
            ))}
          </div>
        </PageContainer>
      </section>

      {/* Modal */}
      {selectedSolution && (
        <Modal
          isOpen={isModalOpen}
          onClose={handleCloseModal}
          title={selectedSolution.title}
          onBack={isCasestudyView ? () => setIsCasestudyView(false) : undefined}
          headerExtra={
            hasCasestudyContent && !isCasestudyView ? (
              <button
                type="button"
                onClick={() => setIsCasestudyView(true)}
                className="text-[#2F78C4] font-semibold text-[18px] leading-[24px] underline hover:text-[#1a5a9b] transition-colors"
              >
                CaseStudy
              </button>
            ) : null
          }
        >
          <SolutionDetailsModal
            solution={selectedSolution}
            isCasestudyView={isCasestudyView}
          />
        </Modal>
      )}

      <Footer />
    </div>
  );
}
